module.exports = [
"[project]/frontend/.next-internal/server/app/contests/[slug]/page/actions.js [app-rsc] (server actions loader, ecmascript)", ((__turbopack_context__, module, exports) => {

}),
"[project]/frontend/app/favicon.ico.mjs { IMAGE => \"[project]/frontend/app/favicon.ico (static in ecmascript)\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/frontend/app/favicon.ico.mjs { IMAGE => \"[project]/frontend/app/favicon.ico (static in ecmascript)\" } [app-rsc] (structured image object, ecmascript)"));
}),
"[project]/frontend/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/frontend/app/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/frontend/components/header.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "Header",
    ()=>Header
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const Header = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call Header() from the server but Header is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/frontend/components/header.tsx <module evaluation>", "Header");
}),
"[project]/frontend/components/header.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "Header",
    ()=>Header
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const Header = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call Header() from the server but Header is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/frontend/components/header.tsx", "Header");
}),
"[project]/frontend/components/header.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$components$2f$header$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/frontend/components/header.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$components$2f$header$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/frontend/components/header.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$components$2f$header$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/frontend/components/footer.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "Footer",
    ()=>Footer
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const Footer = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call Footer() from the server but Footer is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/frontend/components/footer.tsx <module evaluation>", "Footer");
}),
"[project]/frontend/components/footer.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "Footer",
    ()=>Footer
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const Footer = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call Footer() from the server but Footer is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/frontend/components/footer.tsx", "Footer");
}),
"[project]/frontend/components/footer.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$components$2f$footer$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/frontend/components/footer.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$components$2f$footer$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/frontend/components/footer.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$components$2f$footer$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/frontend/content/contest-details.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "eligibilityByContest",
    ()=>eligibilityByContest,
    "overviewOverview",
    ()=>overviewOverview,
    "structureByContest",
    ()=>structureByContest,
    "syllabusByContest",
    ()=>syllabusByContest
]);
const eligibilityByContest = {
    "upsc-elite": "Open to all candidates preparing for the UPSC Civil Services Examination. No age restriction, but recommended for serious aspirants who have completed basic graduation modules. The calibration matches actual Civil Services Prelims complexity parameters.",
    "jee-advanced": "Open to engineering aspirants preparing for JEE Advanced. Ideally suited for students in Grade 12 or drop years targeting Top 500 IIT ranks. Analytical complexity requires deep calculus and logical deduction capacity.",
    "neet-prime": "Open to medical aspirants preparing for NEET-UG. suited for Grade 12 or dropper candidates looking to verify their Speed-Accuracy coefficient across Biology, Chemistry, and Physics."
};
const structureByContest = {
    "upsc-elite": [
        "General Studies Paper I: 100 Objective Questions | 200 Marks | 2-hour duration.",
        "Negative marking applies: -0.66 marks for every wrong response.",
        "Questions span Current Affairs, Indian History, Geography, Polity, Economics, and Environmental Science.",
        "Proctored lockdown protocol requires active webcam connection throughout."
    ],
    "jee-advanced": [
        "Combined PC&M Paper: Physics, Chemistry, and Mathematics sections.",
        "Total Questions: 54 (18 questions per subject) | 180 Marks | 3-hour duration.",
        "Marking scheme features single correct options, multiple correct options (with partial marking), and numerical values.",
        "Sandboxed virtual calculator provided."
    ],
    "neet-prime": [
        "Single Paper: Physics (50 questions), Chemistry (50 questions), Botany (50 questions), and Zoology (50 questions).",
        "Total of 200 questions out of which 180 must be answered.",
        "Standard marking: +4 for correct option, -1 for incorrect option.",
        "Duration: 3 hours and 20 minutes."
    ]
};
const syllabusByContest = {
    "upsc-elite": [
        {
            subject: "Indian Polity & Governance",
            chapters: [
                {
                    name: "Constitutional Framework",
                    topics: [
                        "Fundamental Rights",
                        "Directive Principles",
                        "Amendments"
                    ],
                    weightage: 35,
                    difficulty: "Hard"
                },
                {
                    name: "System of Government",
                    topics: [
                        "Parliamentary System",
                        "Federal Structure",
                        "Centre-State Relations"
                    ],
                    weightage: 30,
                    difficulty: "Medium"
                },
                {
                    name: "Judiciary & Panchayati Raj",
                    topics: [
                        "Supreme Court",
                        "High Courts",
                        "73rd and 74th Amendments"
                    ],
                    weightage: 35,
                    difficulty: "Medium"
                }
            ],
            difficultyDistribution: {
                Easy: 20,
                Medium: 50,
                Hard: 30
            }
        },
        {
            subject: "Indian History & National Movement",
            chapters: [
                {
                    name: "Modern History",
                    topics: [
                        "1857 Revolt",
                        "Indian National Congress",
                        "Gandhian Era"
                    ],
                    weightage: 50,
                    difficulty: "Hard"
                },
                {
                    name: "Ancient & Medieval India",
                    topics: [
                        "Indus Valley",
                        "Mauryas & Guptas",
                        "Mughal Empire"
                    ],
                    weightage: 30,
                    difficulty: "Medium"
                },
                {
                    name: "Art & Culture",
                    topics: [
                        "Temple Architecture",
                        "Classical Dances",
                        "Literature"
                    ],
                    weightage: 20,
                    difficulty: "Hard"
                }
            ],
            difficultyDistribution: {
                Easy: 10,
                Medium: 40,
                Hard: 50
            }
        },
        {
            subject: "Geography & Ecology",
            chapters: [
                {
                    name: "Physical Geography",
                    topics: [
                        "Geomorphology",
                        "Climatology",
                        "Oceanography"
                    ],
                    weightage: 40,
                    difficulty: "Medium"
                },
                {
                    name: "Ecology & Climate Change",
                    topics: [
                        "Biodiversity",
                        "International Conventions",
                        "Pollution Control"
                    ],
                    weightage: 60,
                    difficulty: "Hard"
                }
            ],
            difficultyDistribution: {
                Easy: 30,
                Medium: 30,
                Hard: 40
            }
        }
    ],
    "jee-advanced": [
        {
            subject: "Physics",
            chapters: [
                {
                    name: "Mechanics",
                    topics: [
                        "Rotational Dynamics",
                        "Gravitation",
                        "Fluid Mechanics"
                    ],
                    weightage: 40,
                    difficulty: "Hard"
                },
                {
                    name: "Electromagnetism",
                    topics: [
                        "Electrostatics",
                        "Electromagnetic Induction",
                        "AC Circuits"
                    ],
                    weightage: 40,
                    difficulty: "Hard"
                },
                {
                    name: "Modern Physics",
                    topics: [
                        "Photoelectric Effect",
                        "Radioactivity",
                        "Bohr Model"
                    ],
                    weightage: 20,
                    difficulty: "Medium"
                }
            ],
            difficultyDistribution: {
                Easy: 10,
                Medium: 30,
                Hard: 60
            }
        },
        {
            subject: "Mathematics",
            chapters: [
                {
                    name: "Calculus",
                    topics: [
                        "Limits & Continuity",
                        "Definite Integration",
                        "Differential Equations"
                    ],
                    weightage: 45,
                    difficulty: "Hard"
                },
                {
                    name: "Algebra & Probability",
                    topics: [
                        "Matrices & Determinants",
                        "Probability Distributions",
                        "Complex Numbers"
                    ],
                    weightage: 35,
                    difficulty: "Hard"
                },
                {
                    name: "Coordinate Geometry",
                    topics: [
                        "Conic Sections",
                        "Straight Lines",
                        "Hyperbola"
                    ],
                    weightage: 20,
                    difficulty: "Medium"
                }
            ],
            difficultyDistribution: {
                Easy: 15,
                Medium: 25,
                Hard: 60
            }
        }
    ]
};
const overviewOverview = "This is a premium, proctored competition. Participants must abide by all integrity rules.";
}),
"[project]/frontend/content/contest-rules.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "generalContestRules",
    ()=>generalContestRules,
    "rulesByContest",
    ()=>rulesByContest
]);
const generalContestRules = [
    {
        title: "System Parameters & Integrity",
        description: "Every participant must meet these standard system requirements to participate in active leagues.",
        points: [
            "Operating System must be Windows, macOS, or Linux (mobile and tablets are not supported for Elite/Apex leagues).",
            "Latest version of Google Chrome, Brave, or Safari is required.",
            "Active webcam and microphone access is mandatory for proctoring verification."
        ]
    },
    {
        title: "Active Lockdown Protocol",
        description: "The championship environment enforces a strict lockdown window to ensure absolute fairness.",
        points: [
            "Any tab switch, window minimization, or secondary screen activity will trigger a warning.",
            "Receiving more than 2 warning flags results in automatic disqualification with a status of 'Failed'.",
            "Keyboard shortcuts like Ctrl+C, Ctrl+V, Alt+Tab, and right-click menus are disabled."
        ]
    },
    {
        title: "Timings & Submission Rules",
        description: "Strict adherence to schedule parameters is expected from all participants.",
        points: [
            "Join the arena at least 15 minutes before the scheduled start time for verification setup.",
            "No late entries are permitted after the countdown timer hits 00:00:00.",
            "Automated submission is triggered exactly at the scheduled end time. Leftover questions will not be evaluated."
        ]
    }
];
const rulesByContest = {
    "upsc-elite": [
        {
            title: "UPSC Standard Rules",
            description: "Additional instructions calibrated to UPSC standards.",
            points: [
                "Negative marking is applied: 1/3rd (0.66 marks for Paper I) penalty per incorrect choice.",
                "Both Paper I (GS) and Paper II (CSAT) must be completed to qualify for the verified leaderboard standings.",
                "Minimum qualifying mark for CSAT is 33% (66.67 marks)."
            ]
        }
    ],
    "jee-advanced": [
        {
            title: "JEE Advanced Specific Rules",
            description: "Calibrated marking instructions for JEE Apex competitions.",
            points: [
                "Single-correct, Multiple-correct, and Numerical value questions are present in random distributions.",
                "Negative marking applies to single-correct questions (-1 mark).",
                "Partial marking (+1 or +2) is awarded for multiple-correct questions based on the correctness ratio."
            ]
        }
    ]
};
}),
"[project]/frontend/content/contest-rewards.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "globalRewardsTransparencyNote",
    ()=>globalRewardsTransparencyNote,
    "rewardsByContest",
    ()=>rewardsByContest
]);
const globalRewardsTransparencyNote = "All cash rewards, credit distributions, and certificate issuances are processed through verified standing calculations and audits. Any user flagged for integrity violations will have their rewards frozen pending a manual audit review.";
const rewardsByContest = {
    "upsc-elite": [
        {
            rank: "Rank 1",
            prize: "₹1,50,000 Cash Reward",
            recognition: "National Champion Gold Trophy",
            achievementBadge: "UPSC Supreme Master",
            pointsReward: 10000
        },
        {
            rank: "Rank 2 - 3",
            prize: "₹75,000 Cash Reward",
            recognition: "National Elite Silver Medal",
            achievementBadge: "UPSC Grandmaster",
            pointsReward: 5000
        },
        {
            rank: "Rank 4 - 10",
            prize: "₹25,000 Cash Reward",
            recognition: "National Distinguished Bronze Medal",
            achievementBadge: "UPSC Master",
            pointsReward: 2500
        },
        {
            rank: "Top 1% Percentile",
            prize: "₹5,000 Cash Reward",
            recognition: "Verified Standing Certificate of Excellence",
            achievementBadge: "1st Percentile Club",
            pointsReward: 1000
        },
        {
            rank: "Top 5% Percentile",
            prize: "₹1,000 Credits Package",
            recognition: "Verified Academic Standing Certificate",
            achievementBadge: "5th Percentile Club",
            pointsReward: 500
        }
    ],
    "jee-advanced": [
        {
            rank: "Rank 1",
            prize: "₹2,000,00 Cash Reward",
            recognition: "IIT JEE Apex Champion Trophy",
            achievementBadge: "Apex Scholar Gold",
            pointsReward: 15000
        },
        {
            rank: "Rank 2 - 5",
            prize: "₹1,00,000 Cash Reward",
            recognition: "Apex Scholar Silver Medal",
            achievementBadge: "Apex Scholar Silver",
            pointsReward: 7500
        },
        {
            rank: "Rank 6 - 20",
            prize: "₹30,000 Cash Reward",
            recognition: "Apex Scholar Bronze Medal",
            achievementBadge: "Apex Scholar Bronze",
            pointsReward: 3000
        },
        {
            rank: "Top 1% Percentile",
            prize: "₹5,000 Cash Reward",
            recognition: "Verified Apex Standing Certificate",
            achievementBadge: "Apex 1% Club",
            pointsReward: 1500
        }
    ],
    "neet-prime": [
        {
            rank: "Rank 1",
            prize: "₹1,50,000 Cash Reward",
            recognition: "NEET Prime Cup Gold Trophy",
            achievementBadge: "Med Supreme Gold",
            pointsReward: 12000
        },
        {
            rank: "Rank 2 - 3",
            prize: "₹75,000 Cash Reward",
            recognition: "Med Prime Silver Medal",
            achievementBadge: "Med Supreme Silver",
            pointsReward: 6000
        },
        {
            rank: "Rank 4 - 10",
            prize: "₹20,000 Cash Reward",
            recognition: "Med Prime Bronze Medal",
            achievementBadge: "Med Supreme Bronze",
            pointsReward: 2500
        }
    ]
};
}),
"[project]/frontend/content/contest-schedule.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "globalScheduleGuidelines",
    ()=>globalScheduleGuidelines,
    "scheduleByContest",
    ()=>scheduleByContest
]);
const globalScheduleGuidelines = "Leagues commence dynamically on the specified starting second. Make sure to log in 15 minutes early to finalize camera verification parameters and browser lockdown permissions.";
const scheduleByContest = {
    "upsc-elite": [
        {
            step: "Arena Check-In & Identity Verification",
            time: "09:15 AM",
            description: "Lockdown engine activates. Webcam, browser focus check, and identity verification modules are initialized.",
            status: "completed"
        },
        {
            step: "Paper I (General Studies) Release",
            time: "09:30 AM",
            description: "General Studies question bank unlocked. Timing countdown triggers. 100 high-fidelity UPSC Preliminary questions are loaded.",
            status: "active"
        },
        {
            step: "Mid-Term Review & Integrity Validation",
            time: "10:30 AM",
            description: "Webcam parameters validated. Standing snapshot verification checks completed.",
            status: "upcoming"
        },
        {
            step: "Paper I Completed & Automatic Upload",
            time: "11:30 AM",
            description: "Submission window closes. Answer scripts are archived, and RLS keys locked down.",
            status: "upcoming"
        }
    ],
    "jee-advanced": [
        {
            step: "Identity Verification & Setup Check",
            time: "01:45 PM",
            description: "Browser sandbox mode initializes. Keyboard shortcut inhibitors checked.",
            status: "completed"
        },
        {
            step: "IIT JEE Advanced Apex Arena Launch",
            time: "02:00 PM",
            description: "Official contest workspace unlocked. Numerical response variables and multi-correct choice sections active.",
            status: "active"
        },
        {
            step: "Automated Evaluation & Standing Process",
            time: "05:00 PM",
            description: "Testing concludes. Evaluators and standing generators compute marks and partial-marks allocations.",
            status: "upcoming"
        }
    ],
    "neet-prime": [
        {
            step: "Medical Prime Proctored Portal Access",
            time: "09:45 AM",
            description: "Biometric and identity checks. Zoom / proctor camera feed checked.",
            status: "completed"
        },
        {
            step: "Biology, Physics & Chemistry Cup Commences",
            time: "10:00 AM",
            description: "200 medical objective questions unlocked. Answer panels initialized.",
            status: "active"
        },
        {
            step: "Championship Window Closed",
            time: "01:20 PM",
            description: "All candidate scripts stored. RLS security locked.",
            status: "upcoming"
        }
    ]
};
}),
"[project]/frontend/content/contest-faq.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "contestSpecificFAQs",
    ()=>contestSpecificFAQs,
    "globalFAQContent",
    ()=>globalFAQContent
]);
const globalFAQContent = [
    {
        question: "What is a Championship on Ranker's League?",
        answer: "A Championship is a scheduled, high-fidelity competitive arena replicating the exact rules, syllabus boundaries, and difficulty thresholds of national competitive examinations. Participants compete simultaneously under active proctoring lockdown protocols to establish verified percentiles.",
        category: "General"
    },
    {
        question: "How is Row-Level Security (RLS) and data privacy maintained?",
        answer: "Every query from our frontend and API server layers goes through strict security parameter verification against Supabase. RLS policies are enabled by default across all standing tables, ensuring user data can only be modified by authentic verified sessions while public records remain transparently auditable.",
        category: "Security"
    },
    {
        question: "What are the rules regarding lockdown mode?",
        answer: "To ensure absolute academic integrity and trust, our competition interface enforces full browser lockdown. Switching tabs, opening dev tools, or losing screen focus for more than 3 seconds triggers an automatic verification flag, and repeated violations lead to immediate disqualified standing status.",
        category: "Integrity"
    },
    {
        question: "How are the rewards distributed?",
        answer: "Rewards are automatically calculated and processed via our backend standing adapter within 24 hours of contest completion. Top ranks receive direct prize pools, gold/silver certificates, and verified standing credentials visible on their public profiles.",
        category: "Rewards"
    }
];
const contestSpecificFAQs = {
    "upsc-elite": [
        {
            question: "Is there negative marking in the Civil Services Elite League?",
            answer: "Yes, exactly like the actual UPSC CSE Prelims. A penalty of 1/3rd of the marks assigned to that question is deducted for every incorrect response.",
            category: "Syllabus & Rules"
        },
        {
            question: "Are calculator modules permitted?",
            answer: "Calculators are strictly prohibited. External aids of any kind will result in instant disqualification.",
            category: "Guidelines"
        }
    ],
    "jee-advanced": [
        {
            question: "How does partial marking work in the IIT JEE Advanced Apex Championship?",
            answer: "We support precise partial marking rules for multi-correct choice questions. If a question has options A, B, and C correct, selecting only A and B awards partial positive marks, provided no incorrect options are marked.",
            category: "Syllabus & Rules"
        },
        {
            question: "Is there a virtual calculator provided?",
            answer: "Yes, a standardized virtual calculator matching the IIT JEE Advanced interface will be available inside the lock-in exam terminal.",
            category: "Guidelines"
        }
    ]
};
}),
"[project]/frontend/content/contests.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "contestsContent",
    ()=>contestsContent
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$details$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/frontend/content/contest-details.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$rules$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/frontend/content/contest-rules.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$rewards$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/frontend/content/contest-rewards.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$schedule$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/frontend/content/contest-schedule.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$faq$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/frontend/content/contest-faq.ts [app-rsc] (ecmascript)");
;
;
;
;
;
const contestsContent = [
    {
        id: "upsc-elite",
        slug: "upsc-elite",
        title: "Civil Services Elite League",
        exam: "UPSC CSE Prelims",
        category: "Civil Services",
        entryFee: 499,
        prizePool: 500000,
        participants: 38492,
        maxParticipants: 50000,
        difficulty: "Elite",
        date: "July 12, 2026",
        time: "09:30 AM",
        duration: "2h 00m",
        seatsAvailable: 11508,
        status: "upcoming",
        bannerGradient: "from-amber-500/20 via-yellow-500/10 to-transparent",
        language: "English",
        country: "India",
        isFeatured: true,
        isTrending: true,
        registrationDeadline: "July 11, 2026 11:59 PM",
        overview: "A high-fidelity replication of the UPSC Civil Services Preliminary examination. This championship features paper sets calibrated to replicate actual UPSC complexity parameters to help candidates verify their national standing percentile.",
        eligibility: __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$details$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["eligibilityByContest"]["upsc-elite"],
        structure: __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$details$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["structureByContest"]["upsc-elite"],
        syllabus: __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$details$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["syllabusByContest"]["upsc-elite"],
        rewards: __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$rewards$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["rewardsByContest"]["upsc-elite"],
        rules: [
            ...__TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$rules$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["generalContestRules"][1].points,
            ...__TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$rules$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["rulesByContest"]["upsc-elite"][0].points
        ],
        timeline: __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$schedule$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["scheduleByContest"]["upsc-elite"],
        faq: [
            ...__TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$faq$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["globalFAQContent"],
            ...__TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$faq$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["contestSpecificFAQs"]["upsc-elite"]
        ]
    },
    {
        id: "jee-advanced",
        slug: "jee-advanced",
        title: "IIT JEE Advanced Apex Championship",
        exam: "JEE Advanced",
        category: "Engineering",
        entryFee: 349,
        prizePool: 750000,
        participants: 52100,
        maxParticipants: 80000,
        difficulty: "Apex",
        date: "July 15, 2026",
        time: "02:00 PM",
        duration: "3h 00m",
        seatsAvailable: 27900,
        status: "upcoming",
        bannerGradient: "from-violet-500/20 via-purple-500/10 to-transparent",
        language: "English & Hindi",
        country: "India",
        isFeatured: true,
        isTrending: true,
        registrationDeadline: "July 14, 2026 11:59 PM",
        overview: "Engineering entrance championship built to evaluate analytical capacity under strict time frames. Questions are drafted by experienced IIT educators to simulate authentic JEE Advanced constraints.",
        eligibility: __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$details$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["eligibilityByContest"]["jee-advanced"],
        structure: __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$details$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["structureByContest"]["jee-advanced"],
        syllabus: __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$details$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["syllabusByContest"]["jee-advanced"],
        rewards: __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$rewards$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["rewardsByContest"]["jee-advanced"],
        rules: [
            ...__TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$rules$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["generalContestRules"][1].points,
            ...__TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$rules$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["rulesByContest"]["jee-advanced"][0].points
        ],
        timeline: __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$schedule$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["scheduleByContest"]["jee-advanced"],
        faq: [
            ...__TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$faq$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["globalFAQContent"],
            ...__TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$faq$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["contestSpecificFAQs"]["jee-advanced"]
        ]
    },
    {
        id: "neet-prime",
        slug: "neet-prime",
        title: "NEET Medical Prime Cup",
        exam: "NEET UG",
        category: "Medical Sciences",
        entryFee: 299,
        prizePool: 600000,
        participants: 45900,
        maxParticipants: 60000,
        difficulty: "Prime",
        date: "July 18, 2026",
        time: "10:00 AM",
        duration: "3h 20m",
        seatsAvailable: 14100,
        status: "upcoming",
        bannerGradient: "from-rose-500/20 via-pink-500/10 to-transparent",
        language: "English",
        country: "India",
        isFeatured: true,
        isTrending: false,
        registrationDeadline: "July 17, 2026 11:59 PM",
        overview: "Medical sciences entrance replica evaluating speed, recall depth, and precision parameters across Biology, Chemistry, and Physics subjects.",
        eligibility: __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$details$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["eligibilityByContest"]["neet-prime"],
        structure: __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$details$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["structureByContest"]["neet-prime"],
        syllabus: [],
        rewards: __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$rewards$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["rewardsByContest"]["neet-prime"],
        rules: [
            ...__TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$rules$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["generalContestRules"][1].points
        ],
        timeline: __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$schedule$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["scheduleByContest"]["neet-prime"],
        faq: __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$faq$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["globalFAQContent"]
    },
    {
        id: "finance-league",
        slug: "finance-league",
        title: "Quantitative Finance League Arena",
        exam: "Financial Risk Manager (FRM)",
        category: "Finance & Accounting",
        entryFee: 250,
        prizePool: 250000,
        participants: 8400,
        maxParticipants: 10000,
        difficulty: "Challenger",
        date: "July 20, 2026",
        time: "04:00 PM",
        duration: "1h 30m",
        seatsAvailable: 1600,
        status: "upcoming",
        bannerGradient: "from-emerald-500/20 via-teal-500/10 to-transparent",
        language: "English",
        country: "International",
        isFeatured: false,
        isTrending: true,
        registrationDeadline: "July 19, 2026 11:59 PM",
        overview: "A specialized risk assessment league evaluating portfolio management, options pricing, and actuarial probability theory under high pressure.",
        eligibility: "Finance students, MBA graduates, and CFA/FRM candidates.",
        structure: [
            "50 Quantitative Multiple Choice Questions.",
            "No negative marking.",
            "Proctored zoom feed not required, sandbox lockdown active."
        ],
        syllabus: [],
        rewards: [
            {
                rank: "Rank 1",
                prize: "₹50,000 Credits Package",
                recognition: "Gold Portfolio manager badge"
            },
            {
                rank: "Top 5%",
                prize: "₹5,000 Credits Package",
                recognition: "Verified Risk specialist standing"
            }
        ],
        rules: [
            ...__TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$rules$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["generalContestRules"][1].points
        ],
        timeline: [
            {
                step: "Lockdown validation",
                time: "03:45 PM",
                description: "Verification check",
                status: "completed"
            },
            {
                step: "Quantitative Finance release",
                time: "04:00 PM",
                description: "Exam commencing",
                status: "active"
            }
        ],
        faq: __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$faq$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["globalFAQContent"]
    },
    {
        id: "law-jurisprudence",
        slug: "law-jurisprudence",
        title: "Constitutional Law Jurisprudence Challenge",
        exam: "CLAT PG",
        category: "Law",
        entryFee: 199,
        prizePool: 300000,
        participants: 4100,
        maxParticipants: 5000,
        difficulty: "Prime",
        date: "July 05, 2026",
        time: "11:00 AM",
        duration: "2h 00m",
        seatsAvailable: 0,
        status: "completed",
        bannerGradient: "from-blue-500/20 via-sky-500/10 to-transparent",
        language: "English",
        country: "India",
        isFeatured: false,
        isTrending: false,
        registrationDeadline: "July 04, 2026 11:59 PM",
        overview: "Comprehensive law league focusing on constitutional jurisprudence, legal reasoning, case analysis, and judicial interpretations.",
        eligibility: "LLB / LLM students or candidates preparing for CLAT PG.",
        structure: [
            "120 questions split into objective law queries.",
            "Negative marking of 0.25 penalty per wrong option."
        ],
        syllabus: [],
        rewards: [
            {
                rank: "Rank 1",
                prize: "₹50,000 Cash Reward",
                recognition: "Supreme Advocate Gold Certificate"
            }
        ],
        rules: [
            ...__TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$rules$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["generalContestRules"][1].points
        ],
        timeline: [
            {
                step: "Championship Completed",
                time: "01:00 PM",
                description: "Evaluated successfully and standings posted.",
                status: "completed"
            }
        ],
        faq: __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$faq$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["globalFAQContent"]
    }
];
}),
"[project]/frontend/repositories/ContestRepository.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "ContestAdapter",
    ()=>ContestAdapter,
    "MockContestRepository",
    ()=>MockContestRepository,
    "contestRepository",
    ()=>contestRepository
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contests$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/frontend/content/contests.ts [app-rsc] (ecmascript)");
;
class ContestAdapter {
    static toFrontendContest(db) {
        const seatsAvailable = db.max_participants - db.current_participants;
        // Map difficulty tier enum to UI string
        let difficulty = "Prime";
        if (db.difficulty_tier === "elite") difficulty = "Elite";
        else if (db.difficulty_tier === "apex") difficulty = "Apex";
        // Format display dates/times
        const startDate = new Date(db.scheduled_start);
        const months = [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December"
        ];
        const formattedDate = `${months[startDate.getMonth()]} ${startDate.getDate()}, ${startDate.getFullYear()}`;
        let hours = startDate.getHours();
        const minutes = String(startDate.getMinutes()).padStart(2, "0");
        const ampm = hours >= 12 ? "PM" : "AM";
        hours = hours % 12;
        hours = hours ? hours : 12; // the hour '0' should be '12'
        const formattedTime = `${String(hours).padStart(2, "0")}:${minutes} ${ampm}`;
        // Calculate duration in text
        const endDate = new Date(db.scheduled_end);
        const diffMs = endDate.getTime() - startDate.getTime();
        const diffHrs = Math.floor(diffMs / (1000 * 60 * 60));
        const diffMins = Math.floor(diffMs / (1000 * 60) % 60);
        const durationStr = `${diffHrs}h ${String(diffMins).padStart(2, "0")}m`;
        // Registration deadline is typically 1 hour before scheduled start
        const deadlineDate = new Date(startDate.getTime() - 60 * 60 * 1000);
        const formattedDeadline = `${months[deadlineDate.getMonth()]} ${deadlineDate.getDate()}, ${deadlineDate.getFullYear()} ${String(deadlineDate.getHours() % 12 || 12).padStart(2, "0")}:${String(deadlineDate.getMinutes()).padStart(2, "0")} ${deadlineDate.getHours() >= 12 ? "PM" : "AM"}`;
        return {
            id: db.id,
            slug: db.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)+/g, ""),
            title: db.title,
            exam: db.category === "Civil Services" ? "UPSC CSE Prelims" : db.category === "Engineering" ? "JEE Advanced" : "NEET UG",
            category: db.category,
            entryFee: db.entry_fee_credits,
            prizePool: db.rewards_pool_credits,
            participants: db.current_participants,
            maxParticipants: db.max_participants,
            difficulty,
            date: formattedDate,
            time: formattedTime,
            duration: durationStr,
            seatsAvailable,
            status: db.status,
            bannerGradient: db.category === "Civil Services" ? "from-amber-500/20 via-yellow-500/10 to-transparent" : db.category === "Engineering" ? "from-violet-500/20 via-purple-500/10 to-transparent" : "from-rose-500/20 via-pink-500/10 to-transparent",
            language: "English",
            country: "India",
            isFeatured: db.rewards_pool_credits >= 500000,
            isTrending: db.current_participants >= db.max_participants * 0.7,
            registrationDeadline: formattedDeadline
        };
    }
}
class MockContestRepository {
    async findAll() {
        return __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contests$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["contestsContent"];
    }
    async findBySlug(slug) {
        const contest = __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contests$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["contestsContent"].find((c)=>c.slug === slug);
        if (!contest) return null;
        // In our static content layer, contestsContent is typed as ContestDetail[] which matches this
        return contest;
    }
    async findFeatured() {
        return __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contests$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["contestsContent"].filter((c)=>c.isFeatured);
    }
    async search(query) {
        const q = query.toLowerCase();
        return __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contests$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["contestsContent"].filter((c)=>c.title.toLowerCase().includes(q) || c.exam.toLowerCase().includes(q) || c.category.toLowerCase().includes(q));
    }
}
const contestRepository = new MockContestRepository();
}),
"[project]/frontend/content/contest-categories.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "categoriesContent",
    ()=>categoriesContent
]);
const categoriesContent = [
    {
        id: "civil-services",
        name: "Civil Services",
        description: "National administration championships calibrated to Civil Service standards.",
        iconName: "Globe",
        count: 3
    },
    {
        id: "engineering",
        name: "Engineering",
        description: "Deep analytical and numerical engineering entrance league arenas.",
        iconName: "Binary",
        count: 2
    },
    {
        id: "medical-sciences",
        name: "Medical Sciences",
        description: "High-precision biological and molecular medical league challenges.",
        iconName: "Activity",
        count: 2
    },
    {
        id: "finance",
        name: "Finance & Accounting",
        description: "Quantitative analytics, actuarial and fiscal leagues.",
        iconName: "TrendingUp",
        count: 1
    },
    {
        id: "law",
        name: "Law & Jurisprudence",
        description: "Analytical reasoning and constitutional jurisprudence challenges.",
        iconName: "Scale",
        count: 1
    }
];
}),
"[project]/frontend/content/contest-tags.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "popularSearches",
    ()=>popularSearches,
    "recentSearches",
    ()=>recentSearches,
    "tagsContent",
    ()=>tagsContent
]);
const tagsContent = [
    {
        id: "upsc",
        label: "UPSC CSE",
        category: "exam"
    },
    {
        id: "jee",
        label: "JEE Advanced",
        category: "exam"
    },
    {
        id: "neet",
        label: "NEET UG",
        category: "exam"
    },
    {
        id: "gate",
        label: "GATE CS",
        category: "exam"
    },
    {
        id: "clat",
        label: "CLAT LLM",
        category: "exam"
    },
    {
        id: "polity",
        label: "Polity",
        category: "subject"
    },
    {
        id: "history",
        label: "History",
        category: "subject"
    },
    {
        id: "physics",
        label: "Physics",
        category: "subject"
    },
    {
        id: "chemistry",
        label: "Chemistry",
        category: "subject"
    },
    {
        id: "biology",
        label: "Biology",
        category: "subject"
    },
    {
        id: "maths",
        label: "Mathematics",
        category: "subject"
    },
    {
        id: "finance-tag",
        label: "Corporate Finance",
        category: "subject"
    },
    {
        id: "elite",
        label: "Elite",
        category: "difficulty"
    },
    {
        id: "apex",
        label: "Apex",
        category: "difficulty"
    },
    {
        id: "prime",
        label: "Prime",
        category: "difficulty"
    },
    {
        id: "challenger",
        label: "Challenger",
        category: "difficulty"
    },
    {
        id: "duration-1",
        label: "1h - 2h",
        category: "duration"
    },
    {
        id: "duration-2",
        label: "2h - 3h",
        category: "duration"
    },
    {
        id: "duration-3",
        label: "3h+",
        category: "duration"
    },
    {
        id: "upcoming",
        label: "Upcoming",
        category: "status"
    },
    {
        id: "active",
        label: "Live Soon",
        category: "status"
    },
    {
        id: "completed",
        label: "Completed",
        category: "status"
    }
];
const popularSearches = [
    "UPSC CSE",
    "JEE Advanced",
    "NEET Medical",
    "Free Leagues",
    "Elite Tier",
    "High Prize Pool"
];
const recentSearches = [
    "UPSC Civil Services Prelims",
    "Physics Section Apex",
    "Biology Module Prime"
];
}),
"[project]/frontend/services/ContestService.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "ContestService",
    ()=>ContestService
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$repositories$2f$ContestRepository$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/frontend/repositories/ContestRepository.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$categories$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/frontend/content/contest-categories.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$tags$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/frontend/content/contest-tags.ts [app-rsc] (ecmascript)");
;
;
;
class ContestService {
    static async getAllContests() {
        return __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$repositories$2f$ContestRepository$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["contestRepository"].findAll();
    }
    static async getContestBySlug(slug) {
        return __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$repositories$2f$ContestRepository$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["contestRepository"].findBySlug(slug);
    }
    static async getFeaturedContests() {
        return __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$repositories$2f$ContestRepository$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["contestRepository"].findFeatured();
    }
    static async getCategories() {
        return __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$categories$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["categoriesContent"];
    }
    static async getTags() {
        return __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contest$2d$tags$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["tagsContent"];
    }
    // Orchestrated filter, search, and sort logic inside the service
    static async queryContests(filters) {
        let list = await __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$repositories$2f$ContestRepository$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["contestRepository"].findAll();
        // 1. Search filter
        if (filters.searchTerm) {
            const query = filters.searchTerm.toLowerCase();
            list = list.filter((c)=>c.title.toLowerCase().includes(query) || c.exam.toLowerCase().includes(query) || c.category.toLowerCase().includes(query));
        }
        // 2. Category filter
        if (filters.category && filters.category !== "All") {
            list = list.filter((c)=>c.category.toLowerCase() === filters.category.toLowerCase());
        }
        // 3. Difficulty filter
        if (filters.difficulty && filters.difficulty !== "All") {
            list = list.filter((c)=>c.difficulty.toLowerCase() === filters.difficulty.toLowerCase());
        }
        // 4. Entry Fee filter
        if (filters.entryFeeType && filters.entryFeeType !== "all") {
            if (filters.entryFeeType === "free") {
                list = list.filter((c)=>c.entryFee === 0);
            } else {
                list = list.filter((c)=>c.entryFee > 0);
            }
        }
        // 5. Status filter
        if (filters.status && filters.status !== "All") {
            list = list.filter((c)=>c.status.toLowerCase() === filters.status.toLowerCase());
        }
        // 6. Sorting
        if (filters.sortBy) {
            list = [
                ...list
            ].sort((a, b)=>{
                switch(filters.sortBy){
                    case "newest":
                        return new Date(b.date).getTime() - new Date(a.date).getTime();
                    case "prize-desc":
                        return b.prizePool - a.prizePool;
                    case "fee-asc":
                        return a.entryFee - b.entryFee;
                    case "fee-desc":
                        return b.entryFee - a.entryFee;
                    case "closing-soon":
                        return new Date(a.registrationDeadline).getTime() - new Date(b.registrationDeadline).getTime();
                    case "participants-desc":
                        return b.participants - a.participants;
                    default:
                        return 0;
                }
            });
        }
        return list;
    }
}
}),
"[project]/frontend/components/contests/ContestDetailsClient.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "ContestDetailsClient",
    ()=>ContestDetailsClient,
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const ContestDetailsClient = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call ContestDetailsClient() from the server but ContestDetailsClient is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/frontend/components/contests/ContestDetailsClient.tsx <module evaluation>", "ContestDetailsClient");
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/frontend/components/contests/ContestDetailsClient.tsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/frontend/components/contests/ContestDetailsClient.tsx <module evaluation>", "default");
}),
"[project]/frontend/components/contests/ContestDetailsClient.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "ContestDetailsClient",
    ()=>ContestDetailsClient,
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const ContestDetailsClient = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call ContestDetailsClient() from the server but ContestDetailsClient is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/frontend/components/contests/ContestDetailsClient.tsx", "ContestDetailsClient");
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/frontend/components/contests/ContestDetailsClient.tsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/frontend/components/contests/ContestDetailsClient.tsx", "default");
}),
"[project]/frontend/components/contests/ContestDetailsClient.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$components$2f$contests$2f$ContestDetailsClient$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/frontend/components/contests/ContestDetailsClient.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$components$2f$contests$2f$ContestDetailsClient$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/frontend/components/contests/ContestDetailsClient.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$components$2f$contests$2f$ContestDetailsClient$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/frontend/app/contests/[slug]/page.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>ContestDetailsPage,
    "generateMetadata",
    ()=>generateMetadata,
    "generateStaticParams",
    ()=>generateStaticParams
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$api$2f$navigation$2e$react$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__$3c$locals$3e$__ = __turbopack_context__.i("[project]/node_modules/next/dist/api/navigation.react-server.js [app-rsc] (ecmascript) <locals>");
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$client$2f$components$2f$navigation$2e$react$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/client/components/navigation.react-server.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$components$2f$header$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/frontend/components/header.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$components$2f$footer$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/frontend/components/footer.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$services$2f$ContestService$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/frontend/services/ContestService.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$components$2f$contests$2f$ContestDetailsClient$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/frontend/components/contests/ContestDetailsClient.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contests$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/frontend/content/contests.ts [app-rsc] (ecmascript)");
;
;
;
;
;
;
;
async function generateStaticParams() {
    return __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$content$2f$contests$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["contestsContent"].map((c)=>({
            slug: c.slug
        }));
}
async function generateMetadata({ params }) {
    const { slug } = await params;
    const contest = await __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$services$2f$ContestService$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ContestService"].getContestBySlug(slug);
    if (!contest) {
        return {
            title: "Championship Not Found | Ranker's League"
        };
    }
    const siteUrl = "https://rankersleague.com"; // placeholder canonical host
    const pageUrl = `${siteUrl}/contests/${contest.slug}`;
    return {
        title: `${contest.title} | ${contest.exam} Challenge`,
        description: contest.overview,
        alternates: {
            canonical: pageUrl
        },
        openGraph: {
            title: contest.title,
            description: contest.overview,
            url: pageUrl,
            type: "website",
            images: [
                {
                    url: `${siteUrl}/og-image.png`,
                    width: 1200,
                    height: 630,
                    alt: contest.title
                }
            ]
        },
        twitter: {
            card: "summary_large_image",
            title: contest.title,
            description: contest.overview
        }
    };
}
async function ContestDetailsPage({ params }) {
    const { slug } = await params;
    const contest = await __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$services$2f$ContestService$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ContestService"].getContestBySlug(slug);
    if (!contest) {
        (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$client$2f$components$2f$navigation$2e$react$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["notFound"])();
    }
    // Load related contests
    const allContests = await __TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$services$2f$ContestService$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ContestService"].getAllContests();
    const related = allContests.filter((c)=>c.slug !== slug && (c.category === contest.category || c.isFeatured));
    // Structured Schema.org SEO Markup
    const breadcrumbSchema = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        itemListElement: [
            {
                "@type": "ListItem",
                position: 1,
                name: "Home",
                item: "https://rankersleague.com"
            },
            {
                "@type": "ListItem",
                position: 2,
                name: "Contests",
                item: "https://rankersleague.com/contests"
            },
            {
                "@type": "ListItem",
                position: 3,
                name: contest.title,
                item: `https://rankersleague.com/contests/${contest.slug}`
            }
        ]
    };
    const contestSchema = {
        "@context": "https://schema.org",
        "@type": "EducationEvent",
        "name": contest.title,
        "description": contest.overview,
        "startDate": new Date(contest.date).toISOString().split('T')[0],
        "eventAttendanceMode": "https://schema.org/OnlineEventAttendanceMode",
        "eventStatus": "https://schema.org/EventScheduled",
        "location": {
            "@type": "VirtualLocation",
            "url": `https://rankersleague.com/contests/${contest.slug}`
        },
        "offers": {
            "@type": "Offer",
            "price": contest.entryFee,
            "priceCurrency": "INR",
            "availability": "https://schema.org/InStock"
        },
        "organizer": {
            "@type": "Organization",
            "name": "Ranker's League",
            "url": "https://rankersleague.com"
        }
    };
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("div", {
        className: "flex flex-col min-h-screen bg-background",
        children: [
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("script", {
                type: "application/ld+json",
                dangerouslySetInnerHTML: {
                    __html: JSON.stringify(breadcrumbSchema)
                }
            }, void 0, false, {
                fileName: "[project]/frontend/app/contests/[slug]/page.tsx",
                lineNumber: 130,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("script", {
                type: "application/ld+json",
                dangerouslySetInnerHTML: {
                    __html: JSON.stringify(contestSchema)
                }
            }, void 0, false, {
                fileName: "[project]/frontend/app/contests/[slug]/page.tsx",
                lineNumber: 134,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$components$2f$header$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["Header"], {}, void 0, false, {
                fileName: "[project]/frontend/app/contests/[slug]/page.tsx",
                lineNumber: 139,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])("main", {
                className: "flex-grow",
                children: /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$components$2f$contests$2f$ContestDetailsClient$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["ContestDetailsClient"], {
                    contest: contest,
                    relatedContests: related
                }, void 0, false, {
                    fileName: "[project]/frontend/app/contests/[slug]/page.tsx",
                    lineNumber: 142,
                    columnNumber: 9
                }, this)
            }, void 0, false, {
                fileName: "[project]/frontend/app/contests/[slug]/page.tsx",
                lineNumber: 141,
                columnNumber: 7
            }, this),
            /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$frontend$2f$components$2f$footer$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["Footer"], {}, void 0, false, {
                fileName: "[project]/frontend/app/contests/[slug]/page.tsx",
                lineNumber: 145,
                columnNumber: 7
            }, this)
        ]
    }, void 0, true, {
        fileName: "[project]/frontend/app/contests/[slug]/page.tsx",
        lineNumber: 128,
        columnNumber: 5
    }, this);
}
}),
"[project]/frontend/app/contests/[slug]/page.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/frontend/app/contests/[slug]/page.tsx [app-rsc] (ecmascript)"));
}),
"[externals]/next/dist/shared/lib/no-fallback-error.external.js [external] (next/dist/shared/lib/no-fallback-error.external.js, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("next/dist/shared/lib/no-fallback-error.external.js", () => require("next/dist/shared/lib/no-fallback-error.external.js"));

module.exports = mod;
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__0a3f9aea._.js.map