export interface LeaderboardEntry {
  rank: number;
  name: string;
  avatarUrl?: string;
  initials: string;
  category: string; // e.g. "upsc", "jee-advanced", "neet", "cat", "bitsat"
  contestSlug?: string;
  contestName?: string;
  contestsCompleted: number;
  totalCombinedMarks: number;
  totalPrizeWon: number;
  score: number;
  maxScore: number;
  country: string; // "india" | "international" | "global"
  countryFlag: string; // Flag emoji
  institution: string;
  achievementBadge: string;
  trend: "up" | "down" | "stable";
  timeframe: "weekly" | "monthly" | "overall";
}

export const leaderboardContests = [
  { id: "all", name: "All Contest Arenas" },
  { id: "jee-main-sprint-001", name: "JEE Main Sprint #001" },
  { id: "upsc-prelims-001", name: "UPSC CSE Prelims Arena #001" },
  { id: "neet-grand-001", name: "NEET UG All-India Sprint #001" },
  { id: "cat-quant-001", name: "CAT Quant Mastery Sprint #001" },
  { id: "bitsat-grand-001", name: "BITSAT Speed Sprint #001" },
];

export const leaderboardData: LeaderboardEntry[] = [
  // 1. UPSC Toppers
  {
    rank: 1,
    name: "Ananya Deshmukh",
    initials: "AD",
    category: "upsc",
    contestSlug: "upsc-prelims-001",
    contestName: "UPSC CSE Prelims Arena #001",
    contestsCompleted: 18,
    totalCombinedMarks: 4820,
    totalPrizeWon: 145000,
    score: 286,
    maxScore: 300,
    country: "india",
    countryFlag: "🇮🇳",
    institution: "St. Stephen's College",
    achievementBadge: "All India Rank 1",
    trend: "up",
    timeframe: "overall"
  },
  {
    rank: 2,
    name: "Rohan Singhal",
    initials: "RS",
    category: "upsc",
    contestSlug: "upsc-prelims-001",
    contestName: "UPSC CSE Prelims Arena #001",
    contestsCompleted: 16,
    totalCombinedMarks: 4350,
    totalPrizeWon: 112000,
    score: 278,
    maxScore: 300,
    country: "india",
    countryFlag: "🇮🇳",
    institution: "IIT Kanpur",
    achievementBadge: "National Elite",
    trend: "stable",
    timeframe: "overall"
  },
  {
    rank: 3,
    name: "Sanya Sen",
    initials: "SS",
    category: "upsc",
    contestSlug: "upsc-prelims-001",
    contestName: "UPSC CSE Prelims Arena #001",
    contestsCompleted: 14,
    totalCombinedMarks: 3920,
    totalPrizeWon: 85000,
    score: 272,
    maxScore: 300,
    country: "india",
    countryFlag: "🇮🇳",
    institution: "JNU Delhi",
    achievementBadge: "Civil Services Elite",
    trend: "down",
    timeframe: "overall"
  },
  {
    rank: 4,
    name: "Aditya Hegde",
    initials: "AH",
    category: "upsc",
    contestSlug: "upsc-prelims-001",
    contestName: "UPSC CSE Prelims Arena #001",
    contestsCompleted: 12,
    totalCombinedMarks: 3240,
    totalPrizeWon: 62000,
    score: 260,
    maxScore: 300,
    country: "india",
    countryFlag: "🇮🇳",
    institution: "RV College of Engineering",
    achievementBadge: "Rising Aspirant",
    trend: "up",
    timeframe: "overall"
  },

  // 2. JEE Advanced / Main Toppers
  {
    rank: 1,
    name: "Priyansh Mehta",
    initials: "PM",
    category: "jee-advanced",
    contestSlug: "jee-main-sprint-001",
    contestName: "JEE Main Sprint #001",
    contestsCompleted: 22,
    totalCombinedMarks: 6940,
    totalPrizeWon: 185000,
    score: 342,
    maxScore: 360,
    country: "india",
    countryFlag: "🇮🇳",
    institution: "IIT Bombay",
    achievementBadge: "Engineering Legend",
    trend: "up",
    timeframe: "overall"
  },
  {
    rank: 2,
    name: "Aravind K.",
    initials: "AK",
    category: "jee-advanced",
    contestSlug: "jee-main-sprint-001",
    contestName: "JEE Main Sprint #001",
    contestsCompleted: 20,
    totalCombinedMarks: 6280,
    totalPrizeWon: 140000,
    score: 336,
    maxScore: 360,
    country: "india",
    countryFlag: "🇮🇳",
    institution: "IIT Madras",
    achievementBadge: "Math Prodigy",
    trend: "stable",
    timeframe: "overall"
  },
  {
    rank: 3,
    name: "David Vance",
    initials: "DV",
    category: "jee-advanced",
    contestSlug: "jee-main-sprint-001",
    contestName: "JEE Main Sprint #001",
    contestsCompleted: 15,
    totalCombinedMarks: 4650,
    totalPrizeWon: 95000,
    score: 320,
    maxScore: 360,
    country: "international",
    countryFlag: "🇺🇸",
    institution: "Stanford Prep",
    achievementBadge: "Overseas Genius",
    trend: "up",
    timeframe: "overall"
  },

  // 3. NEET Toppers
  {
    rank: 1,
    name: "Meera Nair",
    initials: "MN",
    category: "neet",
    contestSlug: "neet-grand-001",
    contestName: "NEET UG All-India Sprint #001",
    contestsCompleted: 25,
    totalCombinedMarks: 8640,
    totalPrizeWon: 210000,
    score: 720,
    maxScore: 720,
    country: "india",
    countryFlag: "🇮🇳",
    institution: "AIIMS Delhi",
    achievementBadge: "Perfect Score 720",
    trend: "stable",
    timeframe: "overall"
  },
  {
    rank: 2,
    name: "Isha Patel",
    initials: "IP",
    category: "neet",
    contestSlug: "neet-grand-001",
    contestName: "NEET UG All-India Sprint #001",
    contestsCompleted: 21,
    totalCombinedMarks: 7420,
    totalPrizeWon: 165000,
    score: 712,
    maxScore: 720,
    country: "india",
    countryFlag: "🇮🇳",
    institution: "MAMC Delhi",
    achievementBadge: "Medical Champion",
    trend: "up",
    timeframe: "overall"
  },
  {
    rank: 3,
    name: "Sarah Lin",
    initials: "SL",
    category: "neet",
    contestSlug: "neet-grand-001",
    contestName: "NEET UG All-India Sprint #001",
    contestsCompleted: 17,
    totalCombinedMarks: 5890,
    totalPrizeWon: 105000,
    score: 700,
    maxScore: 720,
    country: "international",
    countryFlag: "🇸🇬",
    institution: "Singapore National School",
    achievementBadge: "Global Medic Elite",
    trend: "down",
    timeframe: "overall"
  },

  // 4. CAT Toppers
  {
    rank: 1,
    name: "Kabir Verma",
    initials: "KV",
    category: "cat",
    contestSlug: "cat-quant-001",
    contestName: "CAT Quant Mastery Sprint #001",
    contestsCompleted: 19,
    totalCombinedMarks: 3420,
    totalPrizeWon: 130000,
    score: 188,
    maxScore: 198,
    country: "india",
    countryFlag: "🇮🇳",
    institution: "IIM Ahmedabad",
    achievementBadge: "99.99 Percentile",
    trend: "up",
    timeframe: "overall"
  },
  {
    rank: 2,
    name: "Siddharth Rao",
    initials: "SR",
    category: "cat",
    contestSlug: "cat-quant-001",
    contestName: "CAT Quant Mastery Sprint #001",
    contestsCompleted: 16,
    totalCombinedMarks: 2890,
    totalPrizeWon: 98000,
    score: 176,
    maxScore: 198,
    country: "india",
    countryFlag: "🇮🇳",
    institution: "FMS Delhi",
    achievementBadge: "Management Prodigy",
    trend: "stable",
    timeframe: "overall"
  },

  // 5. BITSAT Toppers
  {
    rank: 1,
    name: "Rohan Das",
    initials: "RD",
    category: "bitsat",
    contestSlug: "bitsat-grand-001",
    contestName: "BITSAT Speed Sprint #001",
    contestsCompleted: 18,
    totalCombinedMarks: 5680,
    totalPrizeWon: 125000,
    score: 382,
    maxScore: 390,
    country: "india",
    countryFlag: "🇮🇳",
    institution: "BITS Pilani",
    achievementBadge: "BITSAT Topper",
    trend: "up",
    timeframe: "overall"
  },
  {
    rank: 2,
    name: "Priya Singh",
    initials: "PS",
    category: "bitsat",
    contestSlug: "bitsat-grand-001",
    contestName: "BITSAT Speed Sprint #001",
    contestsCompleted: 14,
    totalCombinedMarks: 4320,
    totalPrizeWon: 82000,
    score: 365,
    maxScore: 390,
    country: "india",
    countryFlag: "🇮🇳",
    institution: "BITS Goa",
    achievementBadge: "Elite Scholar",
    trend: "down",
    timeframe: "overall"
  },

  // Weekly & Monthly variations
  {
    rank: 1,
    name: "Kabir Verma",
    initials: "KV",
    category: "cat",
    contestSlug: "cat-quant-001",
    contestName: "CAT Quant Mastery Sprint #001",
    contestsCompleted: 5,
    totalCombinedMarks: 940,
    totalPrizeWon: 35000,
    score: 188,
    maxScore: 198,
    country: "india",
    countryFlag: "🇮🇳",
    institution: "IIM Ahmedabad",
    achievementBadge: "Weekly Topper",
    trend: "up",
    timeframe: "weekly"
  },
  {
    rank: 2,
    name: "Ananya Deshmukh",
    initials: "AD",
    category: "upsc",
    contestSlug: "upsc-prelims-001",
    contestName: "UPSC CSE Prelims Arena #001",
    contestsCompleted: 4,
    totalCombinedMarks: 1144,
    totalPrizeWon: 28000,
    score: 286,
    maxScore: 300,
    country: "india",
    countryFlag: "🇮🇳",
    institution: "St. Stephen's College",
    achievementBadge: "Weekly Climber",
    trend: "up",
    timeframe: "weekly"
  },
  {
    rank: 3,
    name: "Meera Nair",
    initials: "MN",
    category: "neet",
    contestSlug: "neet-grand-001",
    contestName: "NEET UG All-India Sprint #001",
    contestsCompleted: 6,
    totalCombinedMarks: 2160,
    totalPrizeWon: 42000,
    score: 720,
    maxScore: 720,
    country: "india",
    countryFlag: "🇮🇳",
    institution: "AIIMS Delhi",
    achievementBadge: "Weekly Shield",
    trend: "stable",
    timeframe: "weekly"
  },
  {
    rank: 1,
    name: "Priyansh Mehta",
    initials: "PM",
    category: "jee-advanced",
    contestSlug: "jee-main-sprint-001",
    contestName: "JEE Main Sprint #001",
    contestsCompleted: 12,
    totalCombinedMarks: 4104,
    totalPrizeWon: 95000,
    score: 342,
    maxScore: 360,
    country: "india",
    countryFlag: "🇮🇳",
    institution: "IIT Bombay",
    achievementBadge: "Monthly Champion",
    trend: "up",
    timeframe: "monthly"
  },
  {
    rank: 2,
    name: "Meera Nair",
    initials: "MN",
    category: "neet",
    contestSlug: "neet-grand-001",
    contestName: "NEET UG All-India Sprint #001",
    contestsCompleted: 14,
    totalCombinedMarks: 5040,
    totalPrizeWon: 110000,
    score: 720,
    maxScore: 720,
    country: "india",
    countryFlag: "🇮🇳",
    institution: "AIIMS Delhi",
    achievementBadge: "Monthly Star",
    trend: "stable",
    timeframe: "monthly"
  },
  {
    rank: 3,
    name: "Rohan Singhal",
    initials: "RS",
    category: "upsc",
    contestSlug: "upsc-prelims-001",
    contestName: "UPSC CSE Prelims Arena #001",
    contestsCompleted: 10,
    totalCombinedMarks: 2780,
    totalPrizeWon: 68000,
    score: 278,
    maxScore: 300,
    country: "india",
    countryFlag: "🇮🇳",
    institution: "IIT Kanpur",
    achievementBadge: "Monthly Challenger",
    trend: "up",
    timeframe: "monthly"
  }
];
