import { ContestDetail } from "../types/contests";
import { eligibilityByContest, structureByContest, syllabusByContest } from "./contest-details";
import { rulesByContest, generalContestRules } from "./contest-rules";
import { rewardsByContest } from "./contest-rewards";
import { scheduleByContest } from "./contest-schedule";
import { globalFAQContent, contestSpecificFAQs } from "./contest-faq";

export const contestsContent: ContestDetail[] = [
  // ───────────────────────────────────────────────────────────────────────────
  // 1. ENGINEERING STREAM (JEE MAIN & ADVANCED) - LEVELS 1 TO 5
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "jee-foundation-sprint",
    slug: "jee-foundation-sprint",
    title: "JEE Main Foundation Speed & Accuracy Sprint",
    tagline: "Foundation Sprint",
    level: 1,
    exam: "JEE Main",
    category: "Engineering",
    entryFee: 99,
    prizePool: 103950,
    totalCollection: 148500,
    platformMargin: 44550,
    participants: 1250,
    maxParticipants: 1500,
    seatsAvailable: 250,
    difficulty: "Prime",
    date: "July 12, 2026",
    time: "09:30 AM",
    duration: "1h 30m",
    status: "upcoming",
    bannerGradient: "from-amber-500/20 via-yellow-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 11, 2026 11:59 PM",
    overview: "JEE Main Foundation Speed & Accuracy Sprint is engineered for Class 11 & 12 engineering aspirants seeking rapid problem-solving speed and instant diagnostic accuracy evaluation.",
    eligibility: "Open to Class 11, Class 12 & Dropper JEE Main aspirants.",
    structure: [
      "50 High-Yield Foundational Physics, Chemistry & Math Questions",
      "Instant Speed & Accuracy Diagnostic Report",
      "Proctored lockdown sandbox environment"
    ],
    syllabus: syllabusByContest["jee-advanced"] || [],
    rewards: [
      { rank: "Rank 1", prize: "₹25,000 Cash + JEE Champion Badge", recognition: "National Foundation Winner" },
      { rank: "Rank 2 - 5", prize: "₹10,000 Cash Package", recognition: "Silver Merit Standings" },
      { rank: "Top 20%", prize: "₹250 Credits Back", recognition: "Verified Percentile Certificate" }
    ],
    rules: generalContestRules[1].points,
    timeline: scheduleByContest["jee-advanced"] || [],
    faq: globalFAQContent
  },
  {
    id: "jee-analytical-cup",
    slug: "jee-analytical-cup",
    title: "IIT JEE Advanced Analytical Reasoning Cup",
    tagline: "Analytical Cup",
    level: 2,
    exam: "JEE Advanced",
    category: "Engineering",
    entryFee: 89,
    prizePool: 311500,
    totalCollection: 445000,
    platformMargin: 133500,
    participants: 4120,
    maxParticipants: 5000,
    seatsAvailable: 880,
    difficulty: "Elite",
    date: "July 15, 2026",
    time: "02:00 PM",
    duration: "2h 00m",
    status: "upcoming",
    bannerGradient: "from-blue-500/20 via-sky-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 14, 2026 11:59 PM",
    overview: "IIT JEE Advanced Analytical Reasoning Cup evaluates multi-concept analytical depth. Designed by IIT educators to challenge aspirants with complex multi-step numerical questions.",
    eligibility: "Open to JEE Advanced candidates aiming for Top 5,000 AIR.",
    structure: [
      "60 Advanced Multi-Concept Analytical Questions",
      "Negative marking calibration (-1 per incorrect answer)",
      "Detailed step-by-step video solution analysis post-exam"
    ],
    syllabus: syllabusByContest["jee-advanced"] || [],
    rewards: rewardsByContest["jee-advanced"] || [],
    rules: generalContestRules[1].points,
    timeline: scheduleByContest["jee-advanced"] || [],
    faq: globalFAQContent
  },
  {
    id: "jee-precision-contest",
    slug: "jee-precision-contest",
    title: "All-India JEE Precision Contest",
    tagline: "Precision Arena",
    level: 3,
    exam: "JEE Main & Advanced",
    category: "Engineering",
    entryFee: 79,
    prizePool: 553000,
    totalCollection: 790000,
    platformMargin: 237000,
    participants: 8450,
    maxParticipants: 10000,
    seatsAvailable: 1550,
    difficulty: "Apex",
    date: "July 18, 2026",
    time: "10:00 AM",
    duration: "3h 00m",
    status: "upcoming",
    bannerGradient: "from-violet-500/20 via-purple-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 17, 2026 11:59 PM",
    overview: "All-India JEE Precision Contest replicates official NTA/IIT JEE exam conditions under proctored lockdown for verified national standing percentiles.",
    eligibility: "JEE Main & Advanced aspirants across India.",
    structure: [
      "90 NTA & IIT Pattern Questions across PCM",
      "Full camera & proctored proctoring feed",
      "Audited Row-Level Security percentile evaluation"
    ],
    syllabus: [],
    rewards: [
      { rank: "Rank 1", prize: "₹1,25,000 Cash + Precision Supreme Trophy", recognition: "All-India Topper" }
    ],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 2. CIVIL SERVICES STREAM (UPSC CSE & STATE PCS) - LEVELS 1 TO 5
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "upsc-foundation-sprint",
    slug: "upsc-foundation-sprint",
    title: "UPSC CSE Prelims Foundation Speed Sprint",
    tagline: "Foundation Sprint",
    level: 1,
    exam: "UPSC CSE Prelims",
    category: "Civil Services",
    entryFee: 99,
    prizePool: 103950,
    totalCollection: 148500,
    platformMargin: 44550,
    participants: 1100,
    maxParticipants: 1500,
    seatsAvailable: 400,
    difficulty: "Prime",
    date: "July 12, 2026",
    time: "09:30 AM",
    duration: "1h 30m",
    status: "upcoming",
    bannerGradient: "from-amber-500/20 via-yellow-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 11, 2026 11:59 PM",
    overview: "UPSC CSE Prelims Foundation Speed Sprint tests General Studies GS Paper 1 fundamentals, polity, history, and current affairs recall speed.",
    eligibility: "Open to UPSC CSE & State PCS candidates.",
    structure: [
      "50 General Studies GS-1 Calibrated Questions",
      "Instant Accuracy & Score Analytics",
      "Proctored sandbox environment"
    ],
    syllabus: syllabusByContest["upsc-elite"] || [],
    rewards: rewardsByContest["upsc-elite"] || [],
    rules: generalContestRules[1].points,
    timeline: scheduleByContest["upsc-elite"] || [],
    faq: globalFAQContent
  },
  {
    id: "upsc-analytical-cup",
    slug: "upsc-analytical-cup",
    title: "UPSC Civil Services Analytical Reasoning Cup",
    tagline: "Analytical Cup",
    level: 2,
    exam: "UPSC CSE Prelims",
    category: "Civil Services",
    entryFee: 89,
    prizePool: 311500,
    totalCollection: 445000,
    platformMargin: 133500,
    participants: 3950,
    maxParticipants: 5000,
    seatsAvailable: 1050,
    difficulty: "Elite",
    date: "July 15, 2026",
    time: "02:00 PM",
    duration: "2h 00m",
    status: "upcoming",
    bannerGradient: "from-blue-500/20 via-sky-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 14, 2026 11:59 PM",
    overview: "UPSC Civil Services Analytical Reasoning Cup focuses on statement-based questions, elimination techniques, and economics/environment analytical depth.",
    eligibility: "UPSC Prelims aspirants.",
    structure: [
      "60 Statement-Based GS Questions",
      "Standard UPSC 1/3 Negative Marking"
    ],
    syllabus: [],
    rewards: [],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },
  {
    id: "upsc-precision-contest",
    slug: "upsc-precision-contest",
    title: "All-India UPSC Prelims Precision Contest",
    tagline: "Precision Arena",
    level: 3,
    exam: "UPSC CSE Prelims",
    category: "Civil Services",
    entryFee: 79,
    prizePool: 553000,
    totalCollection: 790000,
    platformMargin: 237000,
    participants: 8100,
    maxParticipants: 10000,
    seatsAvailable: 1900,
    difficulty: "Apex",
    date: "July 18, 2026",
    time: "10:00 AM",
    duration: "2h 00m",
    status: "upcoming",
    bannerGradient: "from-violet-500/20 via-purple-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 17, 2026 11:59 PM",
    overview: "All-India UPSC Prelims Precision Contest features 100 questions modeled on exact UPSC difficulty to provide national merit percentiles.",
    eligibility: "UPSC Civil Services aspirants.",
    structure: [
      "100 GS-1 Questions",
      "Proctored lockdown proctoring"
    ],
    syllabus: [],
    rewards: [],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 3. MEDICAL STREAM (NEET UG & NEET PG) - LEVELS 1 TO 5
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "neet-foundation-sprint",
    slug: "neet-foundation-sprint",
    title: "NEET Medical Foundation Speed Sprint",
    tagline: "Foundation Sprint",
    level: 1,
    exam: "NEET UG",
    category: "Medical Sciences",
    entryFee: 99,
    prizePool: 103950,
    totalCollection: 148500,
    platformMargin: 44550,
    participants: 1300,
    maxParticipants: 1500,
    seatsAvailable: 200,
    difficulty: "Prime",
    date: "July 12, 2026",
    time: "09:30 AM",
    duration: "1h 30m",
    status: "upcoming",
    bannerGradient: "from-amber-500/20 via-yellow-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 11, 2026 11:59 PM",
    overview: "NEET Medical Foundation Speed Sprint tests NCERT Biology, Chemistry, and Physics fundamentals with high-speed recall questions.",
    eligibility: "NEET UG aspirants.",
    structure: [
      "50 NCERT High-Yield Biology, Physics & Chemistry Questions",
      "Instant Score Breakdown"
    ],
    syllabus: syllabusByContest["neet-prime"] || [],
    rewards: rewardsByContest["neet-prime"] || [],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },
  {
    id: "neet-analytical-cup",
    slug: "neet-analytical-cup",
    title: "NEET Medical Analytical Reasoning Cup",
    tagline: "Analytical Cup",
    level: 2,
    exam: "NEET UG",
    category: "Medical Sciences",
    entryFee: 89,
    prizePool: 311500,
    totalCollection: 445000,
    platformMargin: 133500,
    participants: 4200,
    maxParticipants: 5000,
    seatsAvailable: 800,
    difficulty: "Elite",
    date: "July 15, 2026",
    time: "02:00 PM",
    duration: "2h 00m",
    status: "upcoming",
    bannerGradient: "from-blue-500/20 via-sky-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 14, 2026 11:59 PM",
    overview: "NEET Medical Analytical Reasoning Cup evaluates multi-concept Physics numericals and Assertion-Reasoning Biology questions.",
    eligibility: "NEET UG candidates.",
    structure: [
      "60 Assertion-Reasoning & Multi-Step Questions"
    ],
    syllabus: [],
    rewards: [],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },
  {
    id: "neet-precision-contest",
    slug: "neet-precision-contest",
    title: "All-India NEET Precision Contest",
    tagline: "Precision Arena",
    level: 3,
    exam: "NEET UG",
    category: "Medical Sciences",
    entryFee: 79,
    prizePool: 553000,
    totalCollection: 790000,
    platformMargin: 237000,
    participants: 8600,
    maxParticipants: 10000,
    seatsAvailable: 1400,
    difficulty: "Apex",
    date: "July 18, 2026",
    time: "10:00 AM",
    duration: "3h 20m",
    status: "upcoming",
    bannerGradient: "from-rose-500/20 via-pink-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 17, 2026 11:59 PM",
    overview: "All-India NEET Precision Contest simulates official 200-question NTA paper format under strict proctored timer.",
    eligibility: "NEET UG candidates across India.",
    structure: [
      "180 Attemptable Questions across PCB",
      "Full camera proctoring"
    ],
    syllabus: [],
    rewards: [],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 4. MANAGEMENT & LAW STREAMS (CAT / CLAT / GATE)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "cat-analytical-cup",
    slug: "cat-analytical-cup",
    title: "CAT Quantitative & Logic Analytics Cup",
    tagline: "Analytical Cup",
    level: 2,
    exam: "CAT",
    category: "Finance & Management",
    entryFee: 89,
    prizePool: 311500,
    totalCollection: 445000,
    platformMargin: 133500,
    participants: 3400,
    maxParticipants: 5000,
    seatsAvailable: 1600,
    difficulty: "Elite",
    date: "July 20, 2026",
    time: "04:00 PM",
    duration: "2h 00m",
    status: "upcoming",
    bannerGradient: "from-emerald-500/20 via-teal-500/10 to-transparent",
    language: "English",
    country: "International",
    isFeatured: false,
    isTrending: true,
    registrationDeadline: "July 19, 2026 11:59 PM",
    overview: "CAT Quantitative & Logic Analytics Cup evaluates Quantitative Aptitude, Data Interpretation, and Logical Reasoning speed under high time pressure.",
    eligibility: "MBA graduates, CAT & XAT candidates.",
    structure: [
      "66 IIM-Pattern QA & DILR Questions",
      "Sectional Timers"
    ],
    syllabus: [],
    rewards: [],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },
  {
    id: "clat-precision-contest",
    slug: "clat-precision-contest",
    title: "All-India Legal Reasoning & CLAT Contest",
    tagline: "Precision Arena",
    level: 3,
    exam: "CLAT",
    category: "Law",
    entryFee: 79,
    prizePool: 553000,
    totalCollection: 790000,
    platformMargin: 237000,
    participants: 4100,
    maxParticipants: 10000,
    seatsAvailable: 5900,
    difficulty: "Prime",
    date: "July 22, 2026",
    time: "11:00 AM",
    duration: "2h 00m",
    status: "upcoming",
    bannerGradient: "from-sky-500/20 via-blue-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: false,
    isTrending: false,
    registrationDeadline: "July 21, 2026 11:59 PM",
    overview: "All-India Legal Reasoning & CLAT Contest evaluates passage-based legal reasoning, constitutional law, and comprehension.",
    eligibility: "CLAT UG / PG candidates.",
    structure: [
      "120 Passage-Based Legal & Critical Reasoning Questions"
    ],
    syllabus: [],
    rewards: [],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 5. APEX & GRAND NATIONAL CONTESTS - LEVELS 4 & 5
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "national-grandmaster-cup",
    slug: "national-grandmaster-cup",
    title: "National Grandmaster Academic Cup",
    tagline: "Grandmaster Cup",
    level: 4,
    exam: "JEE / NEET / UPSC All-India",
    category: "Engineering & Medical",
    entryFee: 59,
    prizePool: 1032500,
    totalCollection: 1475000,
    platformMargin: 442500,
    participants: 19850,
    maxParticipants: 25000,
    seatsAvailable: 5150,
    difficulty: "Apex",
    date: "July 22, 2026",
    time: "10:00 AM",
    duration: "3h 20m",
    status: "upcoming",
    bannerGradient: "from-emerald-500/20 via-teal-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 21, 2026 11:59 PM",
    overview: "National Grandmaster Academic Cup is the premier national exam cup bringing together 25,000 serious contenders across India for ₹10.32 Lakhs cash pool.",
    eligibility: "Open to all JEE, NEET & UPSC aspirants across India.",
    structure: [
      "100 Grandmaster Level Exam Questions",
      "AI-audited proctoring & fraud protection system",
      "Official Merit Certificates & cash reward payouts for top rankers"
    ],
    syllabus: [],
    rewards: [
      { rank: "Rank 1", prize: "₹2,50,000 Cash + Grandmaster Apex Trophy", recognition: "All-India Champion" },
      { rank: "Rank 2 - 25", prize: "₹25,000 Cash Package", recognition: "Top 25 National Ranks" },
      { rank: "Rank 26 - 250", prize: "₹2,000 Credits", recognition: "Percentile Honor Badge" }
    ],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },
  {
    id: "grand-national-apex-league",
    slug: "grand-national-apex-league",
    title: "Grand National Apex Contest",
    tagline: "Grand National Apex",
    level: 5,
    exam: "Grand National Competition",
    category: "Grand National Tier 5",
    entryFee: 49,
    prizePool: 1715000,
    totalCollection: 2450000,
    platformMargin: 735000,
    participants: 39120,
    maxParticipants: 50000,
    seatsAvailable: 10880,
    difficulty: "Apex",
    date: "July 25, 2026",
    time: "02:00 PM",
    duration: "4h 00m",
    status: "upcoming",
    bannerGradient: "from-rose-500/20 via-pink-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 24, 2026 11:59 PM",
    overview: "Grand National Apex Contest is India's largest national academic contest with 50,000 seat capacity, ₹17.15 Lakhs prize pool, and official Ranker's League Academic Medals.",
    eligibility: "Open to all student contenders across India.",
    structure: [
      "120 Exam Questions across Physics, Chemistry, Math & GK",
      "Full proctored proctoring feed & proctor log",
      "Official Grand National Merit Certificates & Cash Rewards"
    ],
    syllabus: [],
    rewards: [
      { rank: "Rank 1", prize: "₹5,00,000 Cash + National Crown Trophy", recognition: "Grand National Apex Topper" },
      { rank: "Rank 2 - 50", prize: "₹15,000 Cash Package", recognition: "National Merit Laureate" }
    ],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 6. DESIGN STREAM (NID DAT / UCEED / CEED / NIFT)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "uceed-design-master-sprint",
    slug: "uceed-design-master-sprint",
    title: "All-India UCEED & NID Design Master Sprint",
    tagline: "Design Master Sprint",
    level: 2,
    exam: "UCEED",
    category: "Design",
    entryFee: 79,
    prizePool: 250000,
    totalCollection: 350000,
    platformMargin: 100000,
    participants: 2800,
    maxParticipants: 4000,
    seatsAvailable: 1200,
    difficulty: "Elite",
    date: "August 15, 2026",
    time: "10:00 AM",
    duration: "2h 30m",
    status: "upcoming",
    bannerGradient: "from-pink-500/20 via-rose-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "August 14, 2026 11:59 PM",
    overview: "All-India UCEED & NID Design Master Sprint evaluates spatial visualization, observation, design sensitivity, and analytical drawing aptitude.",
    eligibility: "Open to UCEED, NID DAT, CEED & NIFT design aspirants.",
    structure: [
      "50 Visual Reasoning & Design Sensitivity Questions",
      "Digital Sketching Portfolio Assessment",
      "Instant AIR Percentile Rank"
    ],
    syllabus: [],
    rewards: [
      { rank: "Rank 1", prize: "₹50,000 Cash + Design Scholar Trophy", recognition: "National Design Topper" },
      { rank: "Rank 2 - 10", prize: "₹10,000 Cash Package", recognition: "Merit Laureate" }
    ],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 7. COMMERCE STREAM (CA / CMA / CS / ACCA)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "ca-foundation-prestige-cup",
    slug: "ca-foundation-prestige-cup",
    title: "All-India CA Foundation & Inter Prestige Cup",
    tagline: "Commerce Prestige Cup",
    level: 2,
    exam: "CA Foundation",
    category: "Commerce",
    entryFee: 99,
    prizePool: 350000,
    totalCollection: 500000,
    platformMargin: 150000,
    participants: 4100,
    maxParticipants: 6000,
    seatsAvailable: 1900,
    difficulty: "Prime",
    date: "August 18, 2026",
    time: "02:00 PM",
    duration: "3h 00m",
    status: "upcoming",
    bannerGradient: "from-violet-500/20 via-purple-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "August 17, 2026 11:59 PM",
    overview: "All-India CA Foundation & Inter Prestige Cup features accounting principles, business law, mercantile ethics, and corporate mathematics.",
    eligibility: "Open to CA Foundation, CA Inter, CMA & CS candidates.",
    structure: [
      "100 ICAI Pattern Multiple Choice & Problem-Solving Questions",
      "Proctored exam environment",
      "Detailed subject-wise accuracy scorecard"
    ],
    syllabus: [],
    rewards: [
      { rank: "Rank 1", prize: "₹75,000 Cash + ICAI Ranker Shield", recognition: "All-India Topper" },
      { rank: "Rank 2 - 15", prize: "₹12,000 Cash Package", recognition: "National Merit Scholar" }
    ],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 8. DEFENCE STREAM (NDA / CDS / AFCAT / AGNIVEER)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "nda-cds-defence-apex",
    slug: "nda-cds-defence-apex",
    title: "All-India NDA & CDS Defence Valor Contest",
    tagline: "Defence Valor Contest",
    level: 3,
    exam: "NDA",
    category: "Defence",
    entryFee: 49,
    prizePool: 300000,
    totalCollection: 450000,
    platformMargin: 150000,
    participants: 6200,
    maxParticipants: 8000,
    seatsAvailable: 1800,
    difficulty: "Apex",
    date: "August 20, 2026",
    time: "09:00 AM",
    duration: "2h 30m",
    status: "upcoming",
    bannerGradient: "from-indigo-500/20 via-blue-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "August 19, 2026 11:59 PM",
    overview: "All-India NDA & CDS Defence Valor Contest evaluates Mathematics, General Ability (GAT), English comprehension, and military awareness.",
    eligibility: "Open to NDA, CDS, AFCAT & Agniveer candidates across India.",
    structure: [
      "120 UPSC NDA/CDS Pattern Mathematics & GAT Questions",
      "Negative marking (-0.83 per wrong attempt)",
      "National Defence Merit Certificate"
    ],
    syllabus: [],
    rewards: [
      { rank: "Rank 1", prize: "₹60,000 Cash + Military Valor Shield", recognition: "National Cadet Champion" },
      { rank: "Rank 2 - 20", prize: "₹10,000 Cash Package", recognition: "Defence Merit Cadet" }
    ],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 9. OLYMPIADS STREAM (IOQM / SOF / IMO / IPhO)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "international-math-olympiad-cup",
    slug: "international-math-olympiad-cup",
    title: "Global International Math & Science Olympiad Cup",
    tagline: "Global Olympiad Cup",
    level: 4,
    exam: "SOF IMO",
    category: "Olympiads",
    entryFee: 39,
    prizePool: 400000,
    totalCollection: 600000,
    platformMargin: 200000,
    participants: 8900,
    maxParticipants: 12000,
    seatsAvailable: 3100,
    difficulty: "Apex",
    date: "August 22, 2026",
    time: "03:00 PM",
    duration: "2h 00m",
    status: "upcoming",
    bannerGradient: "from-yellow-500/20 via-amber-500/10 to-transparent",
    language: "English",
    country: "Both",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "August 21, 2026 11:59 PM",
    overview: "Global International Math & Science Olympiad Cup tests deep problem solving in geometry, number theory, combinatorics, and physics.",
    eligibility: "Open to School & High School Olympiad contenders globally.",
    structure: [
      "40 Deep Proof-Based & Numerical Problem Challenges",
      "Global Percentile Leaderboard",
      "International Olympiad Medal & Digital Certificate"
    ],
    syllabus: [],
    rewards: [
      { rank: "Rank 1", prize: "₹1,00,000 Cash + International Gold Medal", recognition: "Global Olympiad Topper" },
      { rank: "Rank 2 - 10", prize: "₹20,000 Cash Package + Silver Medal", recognition: "International Laureate" }
    ],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 10. SCHOOL EXAMS (CBSE CLASS 10 & 12 / ICSE / IB / A-LEVELS)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "cbse-class-12-board-sprint",
    slug: "cbse-class-12-board-sprint",
    title: "All-India CBSE & ICSE Class 12 Board Sprint",
    tagline: "Board Sprint",
    level: 1,
    exam: "CBSE Class 12",
    category: "School",
    entryFee: 0,
    prizePool: 150000,
    totalCollection: 150000,
    platformMargin: 0,
    participants: 9500,
    maxParticipants: 15000,
    seatsAvailable: 5500,
    difficulty: "Prime",
    date: "August 24, 2026",
    time: "10:00 AM",
    duration: "3h 00m",
    status: "upcoming",
    bannerGradient: "from-teal-500/20 via-emerald-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: false,
    isTrending: true,
    registrationDeadline: "August 23, 2026 11:59 PM",
    overview: "All-India CBSE & ICSE Class 12 Board Sprint helps students practice sample papers and past 10-year board questions under timed proctoring.",
    eligibility: "Open to Class 10 & 12 Board exam candidates across India.",
    structure: [
      "70 CBSE & State Board Sample Questions",
      "Subject-wise Score Card (Physics, Chemistry, Math, Bio)",
      "Full Answer Explanations"
    ],
    syllabus: [],
    rewards: [
      { rank: "Rank 1", prize: "₹30,000 Cash + School Scholar Trophy", recognition: "National Board Topper" },
      { rank: "Rank 2 - 20", prize: "₹5,000 Cash Package", recognition: "Merit Certificate" }
    ],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 11. ENGLISH PROFICIENCY (IELTS / TOEFL / PTE / DUOLINGO)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "ielts-toefl-english-master-cup",
    slug: "ielts-toefl-english-master-cup",
    title: "Global IELTS & TOEFL English Proficiency Cup",
    tagline: "English Proficiency Cup",
    level: 2,
    exam: "IELTS",
    category: "English",
    entryFee: 49,
    prizePool: 200000,
    totalCollection: 300000,
    platformMargin: 100000,
    participants: 3400,
    maxParticipants: 5000,
    seatsAvailable: 1600,
    difficulty: "Intermediate" as any,
    date: "August 26, 2026",
    time: "04:00 PM",
    duration: "2h 15m",
    status: "upcoming",
    bannerGradient: "from-rose-500/20 via-pink-500/10 to-transparent",
    language: "English",
    country: "Both",
    isFeatured: false,
    isTrending: true,
    registrationDeadline: "August 25, 2026 11:59 PM",
    overview: "Global IELTS & TOEFL English Proficiency Cup tests Reading, Listening, Lexical Resource, and Grammatical Range.",
    eligibility: "Open to international study & visa aspirants.",
    structure: [
      "40 Reading & Grammar Passages",
      "Listening Comprehension Audio Diagnostic",
      "Estimated Band Score 1.0–9.0 Evaluation"
    ],
    syllabus: [],
    rewards: [
      { rank: "Rank 1", prize: "₹40,000 Cash + Band 9.0 Honor Badge", recognition: "Global English Topper" },
      { rank: "Rank 2 - 10", prize: "₹8,000 Cash Package", recognition: "Fluency Merit Winner" }
    ],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 12. PROGRAMMING & CS (ICPC / CODEFORCES / LEETCODE / HACKER CUP)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "algorithmic-grandmaster-code-cup",
    slug: "algorithmic-grandmaster-code-cup",
    title: "Global Algorithmic Code Cup (ICPC & LeetCode Style)",
    tagline: "Code Cup Arena",
    level: 4,
    exam: "ICPC",
    category: "Programming",
    entryFee: 59,
    prizePool: 500000,
    totalCollection: 750000,
    platformMargin: 250000,
    participants: 7800,
    maxParticipants: 10000,
    seatsAvailable: 2200,
    difficulty: "Apex",
    date: "August 28, 2026",
    time: "08:00 PM",
    duration: "3h 00m",
    status: "upcoming",
    bannerGradient: "from-cyan-500/20 via-sky-500/10 to-transparent",
    language: "English",
    country: "Both",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "August 27, 2026 11:59 PM",
    overview: "Global Algorithmic Code Cup tests Data Structures, Dynamic Programming, Graphs, and Computational Complexity under automated judge testing.",
    eligibility: "Open to software engineers, competitive programmers & CS students globally.",
    structure: [
      "6 Algorithmic Problems (Div 1/Div 2 difficulty)",
      "Multi-language Judge Support (C++, Python, Java, Go, Rust)",
      "Real-time AC/WA/TLE Codeforces style scoreboard"
    ],
    syllabus: [],
    rewards: [
      { rank: "Rank 1", prize: "₹1,50,000 Cash + Code Grandmaster Trophy", recognition: "Global Code Champion" },
      { rank: "Rank 2 - 20", prize: "₹15,000 Cash Package", recognition: "Codeforces/ICPC Style Ranker" }
    ],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 13. FINANCE STREAM (FRM / CFA / CFP / FINANCIAL MODELING)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "cfa-frm-finance-apex-contest",
    slug: "cfa-frm-finance-apex-contest",
    title: "All-India CFA & FRM Financial Analytics Contest",
    tagline: "Finance Apex Contest",
    level: 3,
    exam: "CFA Level I",
    category: "Finance",
    entryFee: 99,
    prizePool: 300000,
    totalCollection: 450000,
    platformMargin: 150000,
    participants: 3200,
    maxParticipants: 5000,
    seatsAvailable: 1800,
    difficulty: "Apex",
    date: "August 29, 2026",
    time: "11:00 AM",
    duration: "2h 30m",
    status: "upcoming",
    bannerGradient: "from-green-500/20 via-emerald-500/10 to-transparent",
    language: "English",
    country: "Both",
    isFeatured: false,
    isTrending: true,
    registrationDeadline: "August 28, 2026 11:59 PM",
    overview: "All-India CFA & FRM Financial Analytics Contest tests Portfolio Management, Quantitative Methods, Fixed Income, Derivatives, and Risk Modeling.",
    eligibility: "Open to CFA, FRM & Financial Analysts.",
    structure: [
      "80 CFA Institute Pattern Item-Set Questions",
      "Financial Calculator & Formula Sheet Allowed",
      "National Percentile Benchmark Report"
    ],
    syllabus: [],
    rewards: [
      { rank: "Rank 1", prize: "₹65,000 Cash + Wall Street Charter Badge", recognition: "National Finance Topper" },
      { rank: "Rank 2 - 10", prize: "₹12,000 Cash Package", recognition: "Financial Analyst Ranker" }
    ],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 14. GRADUATE ADMISSIONS (GATE / CSIR NET / UGC NET / IIT JAM / CUET PG)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "gate-cse-mtech-psu-contest",
    slug: "gate-cse-mtech-psu-contest",
    title: "All-India GATE CSE & ECE M.Tech Benchmark Contest",
    tagline: "GATE Benchmark Contest",
    level: 3,
    exam: "GATE",
    category: "Graduate",
    entryFee: 79,
    prizePool: 400000,
    totalCollection: 600000,
    platformMargin: 200000,
    participants: 5800,
    maxParticipants: 8000,
    seatsAvailable: 2200,
    difficulty: "Apex",
    date: "August 30, 2026",
    time: "02:00 PM",
    duration: "3h 00m",
    status: "upcoming",
    bannerGradient: "from-orange-500/20 via-amber-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "August 29, 2026 11:59 PM",
    overview: "All-India GATE CSE & ECE M.Tech Benchmark Contest simulates IISc/IIT GATE online calculator exam environment.",
    eligibility: "Open to B.Tech, M.Sc & GATE 2027 aspirants across India.",
    structure: [
      "65 Official IIT GATE Pattern NAT & MSQ Questions",
      "Virtual Calculator Tool Interface",
      "PSU & IIT Cutoff Estimation Report"
    ],
    syllabus: [],
    rewards: [
      { rank: "Rank 1", prize: "₹80,000 Cash + GATE Gold Rank Trophy", recognition: "AIR 1 GATE Contender" },
      { rank: "Rank 2 - 15", prize: "₹15,000 Cash Package", recognition: "IIT M.Tech Qualified" }
    ],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 15. HIRING ASSESSMENTS (AMAZON OA / GOOGLE OA / TCS NQT / INFOSYS)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "top-tech-faang-oa-hiring-sprint",
    slug: "top-tech-faang-oa-hiring-sprint",
    title: "All-India Top Tech FAANG OA & Placement Hiring Sprint",
    tagline: "Hiring Sprint",
    level: 3,
    exam: "Amazon OA",
    category: "Hiring",
    entryFee: 49,
    prizePool: 350000,
    totalCollection: 500000,
    platformMargin: 150000,
    participants: 7400,
    maxParticipants: 10000,
    seatsAvailable: 2600,
    difficulty: "Elite",
    date: "September 02, 2026",
    time: "07:00 PM",
    duration: "2h 00m",
    status: "upcoming",
    bannerGradient: "from-sky-500/20 via-blue-500/10 to-transparent",
    language: "English",
    country: "Both",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "September 01, 2026 11:59 PM",
    overview: "All-India Top Tech FAANG OA & Placement Hiring Sprint simulates Amazon, Google & Microsoft Online Assessment coding and work-simulation rounds.",
    eligibility: "Open to 2025, 2026 & 2027 batch B.Tech/BCA/MCA campus job aspirants.",
    structure: [
      "2 Hard LC Coding Questions + 1 System Design MCQ",
      "Automated Test Case & Memory Complexity Profiling",
      "FAANG Resume Review Referral for Top Performers"
    ],
    syllabus: [],
    rewards: [
      { rank: "Rank 1", prize: "₹70,000 Cash + Tech Placement Winner Trophy", recognition: "FAANG OA Rank 1" },
      { rank: "Rank 2 - 25", prize: "₹10,000 Cash Package", recognition: "Top Tech Hireable Candidate" }
    ],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 16. INTERNATIONAL GLOBAL ARENAS (SAT / GRE / GMAT / OLYMPIAD / USMLE)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "sat-digital-global-championship",
    slug: "sat-digital-global-championship",
    title: "Global Digital SAT Math & Reading Championship",
    tagline: "Global SAT Arena",
    level: 4,
    exam: "SAT Digital",
    category: "International",
    entryFee: 15,
    prizePool: 10500,
    totalCollection: 15000,
    platformMargin: 4500,
    participants: 780,
    maxParticipants: 1000,
    seatsAvailable: 220,
    difficulty: "Apex",
    date: "August 20, 2026",
    time: "04:00 PM GMT",
    duration: "2h 15m",
    status: "upcoming",
    bannerGradient: "from-blue-600/20 via-indigo-500/10 to-transparent",
    language: "English",
    country: "International",
    regionScope: "international",
    currency: "USD",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "August 19, 2026 11:59 PM GMT",
    overview: "Global Digital SAT Math & Reading Championship benchmarked against College Board's latest adaptive testing protocol for Ivy League & Top Global Uni applicants.",
    eligibility: "Open to international candidates preparing for Digital SAT, PSAT & US/UK University Admissions.",
    structure: [
      "Adaptive Module 1 & Module 2 Math & Reading Sections",
      "Real-time Percentile Rank & Scaled Score Diagnostic (400 - 1600)",
      "Ivy League Merit Certificate for Top 5%"
    ],
    syllabus: [],
    rewards: [
      { rank: "Rank 1", prize: "$2,500 USD Cash + Global SAT Champion Trophy", recognition: "All-World Rank 1" },
      { rank: "Rank 2 - 5", prize: "$1,000 USD Cash Package", recognition: "Global Top Percentile" }
    ],
    rules: generalContestRules[0].points,
    timeline: [],
    faq: globalFAQContent
  },
  {
    id: "gre-quant-mastery-arena",
    slug: "gre-quant-mastery-arena",
    title: "GRE Quantitative Reasoning Global Sprint Arena",
    tagline: "Global GRE Arena",
    level: 3,
    exam: "GRE General",
    category: "International",
    entryFee: 20,
    prizePool: 14000,
    totalCollection: 20000,
    platformMargin: 6000,
    participants: 620,
    maxParticipants: 1000,
    seatsAvailable: 380,
    difficulty: "Elite",
    date: "August 28, 2026",
    time: "06:00 PM GMT",
    duration: "1h 45m",
    status: "upcoming",
    bannerGradient: "from-purple-600/20 via-violet-500/10 to-transparent",
    language: "English",
    country: "International",
    regionScope: "international",
    currency: "USD",
    isFeatured: true,
    isTrending: false,
    registrationDeadline: "August 27, 2026 11:59 PM GMT",
    overview: "GRE Quantitative Reasoning Global Sprint simulates ETS high-difficulty Data Interpretation and Problem Solving sections for MS & STEM Master's candidates worldwide.",
    eligibility: "Open to global graduates applying for MS, PhD & STEM programs in US, Canada & Europe.",
    structure: [
      "40 High-Yield Quantitative Comparison & Multiple-Choice Questions",
      "Instant Sectional Diagnostic Breakdown",
      "Score Estimate (130 - 170 Quant Scale)"
    ],
    syllabus: [],
    rewards: [
      { rank: "Rank 1", prize: "$3,000 USD Cash + GRE Scholar Medallion", recognition: "Global Quant Leader" },
      { rank: "Rank 2 - 10", prize: "$800 USD Cash Package", recognition: "STEM Excellence Award" }
    ],
    rules: generalContestRules[0].points,
    timeline: [],
    faq: globalFAQContent
  },
  {
    id: "imo-international-math-olympiad",
    slug: "imo-international-math-olympiad",
    title: "International Mathematical Olympiad Grand Challenge",
    tagline: "Olympiad Challenge",
    level: 5,
    exam: "Math Olympiad",
    category: "International",
    entryFee: 25,
    prizePool: 24500,
    totalCollection: 35000,
    platformMargin: 10500,
    participants: 1100,
    maxParticipants: 1400,
    seatsAvailable: 300,
    difficulty: "Apex",
    date: "September 05, 2026",
    time: "02:00 PM GMT",
    duration: "3h 00m",
    status: "upcoming",
    bannerGradient: "from-amber-600/20 via-orange-500/10 to-transparent",
    language: "English",
    country: "Both",
    regionScope: "global",
    currency: "USD",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "September 04, 2026 11:59 PM GMT",
    overview: "International Mathematical Olympiad Grand Challenge brings together the sharpest mathematical minds globally for proof-oriented, high-level problem solving.",
    eligibility: "Open globally to school & college math enthusiasts.",
    structure: [
      "6 Proof & Concept-Intensive Higher Mathematics Problems",
      "Evaluated by International Olympiad Mentors",
      "Grandmaster Gold, Silver & Bronze Medals"
    ],
    syllabus: [],
    rewards: [
      { rank: "Rank 1", prize: "$5,000 USD Cash + IMO Gold Medal", recognition: "World Champion" },
      { rank: "Rank 2 - 3", prize: "$2,500 USD Cash + IMO Silver Medals", recognition: "Olympiad Grandmaster" }
    ],
    rules: generalContestRules[0].points,
    timeline: [],
    faq: globalFAQContent
  }
];

