import { ContestDetail } from "../types/contests";
import { eligibilityByContest, structureByContest, syllabusByContest } from "./contest-details";
import { rulesByContest, generalContestRules } from "./contest-rules";
import { rewardsByContest } from "./contest-rewards";
import { scheduleByContest } from "./contest-schedule";
import { globalFAQContent, contestSpecificFAQs } from "./contest-faq";

export const contestsContent: ContestDetail[] = [
  // ───────────────────────────────────────────────────────────────────────────
  // 1. ENGINEERING STREAM (JEE MAIN & ADVANCED) - LEVELS 1 TO 5
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "jee-foundation-sprint",
    slug: "jee-foundation-sprint",
    title: "JEE Main Foundation Speed & Accuracy Sprint",
    tagline: "Foundation Sprint",
    level: 1,
    exam: "JEE Main",
    category: "Engineering",
    entryFee: 99,
    prizePool: 103950,
    totalCollection: 148500,
    platformMargin: 44550,
    participants: 1250,
    maxParticipants: 1500,
    seatsAvailable: 250,
    difficulty: "Prime",
    date: "July 12, 2026",
    time: "09:30 AM",
    duration: "1h 30m",
    status: "upcoming",
    bannerGradient: "from-amber-500/20 via-yellow-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 11, 2026 11:59 PM",
    overview: "JEE Main Foundation Speed & Accuracy Sprint is engineered for Class 11 & 12 engineering aspirants seeking rapid problem-solving speed and instant diagnostic accuracy evaluation.",
    eligibility: "Open to Class 11, Class 12 & Dropper JEE Main aspirants.",
    structure: [
      "50 High-Yield Foundational Physics, Chemistry & Math Questions",
      "Instant Speed & Accuracy Diagnostic Report",
      "Proctored lockdown sandbox environment"
    ],
    syllabus: syllabusByContest["jee-advanced"] || [],
    rewards: [
      { rank: "Rank 1", prize: "₹25,000 Cash + JEE Champion Badge", recognition: "National Foundation Winner" },
      { rank: "Rank 2 - 5", prize: "₹10,000 Cash Package", recognition: "Silver Merit Standings" },
      { rank: "Top 20%", prize: "₹250 Credits Back", recognition: "Verified Percentile Certificate" }
    ],
    rules: generalContestRules[1].points,
    timeline: scheduleByContest["jee-advanced"] || [],
    faq: globalFAQContent
  },
  {
    id: "jee-analytical-cup",
    slug: "jee-analytical-cup",
    title: "IIT JEE Advanced Analytical Reasoning Cup",
    tagline: "Analytical Cup",
    level: 2,
    exam: "JEE Advanced",
    category: "Engineering",
    entryFee: 89,
    prizePool: 311500,
    totalCollection: 445000,
    platformMargin: 133500,
    participants: 4120,
    maxParticipants: 5000,
    seatsAvailable: 880,
    difficulty: "Elite",
    date: "July 15, 2026",
    time: "02:00 PM",
    duration: "2h 00m",
    status: "upcoming",
    bannerGradient: "from-blue-500/20 via-sky-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 14, 2026 11:59 PM",
    overview: "IIT JEE Advanced Analytical Reasoning Cup evaluates multi-concept analytical depth. Designed by IIT educators to challenge aspirants with complex multi-step numerical questions.",
    eligibility: "Open to JEE Advanced candidates aiming for Top 5,000 AIR.",
    structure: [
      "60 Advanced Multi-Concept Analytical Questions",
      "Negative marking calibration (-1 per incorrect answer)",
      "Detailed step-by-step video solution analysis post-exam"
    ],
    syllabus: syllabusByContest["jee-advanced"] || [],
    rewards: rewardsByContest["jee-advanced"] || [],
    rules: generalContestRules[1].points,
    timeline: scheduleByContest["jee-advanced"] || [],
    faq: globalFAQContent
  },
  {
    id: "jee-precision-contest",
    slug: "jee-precision-contest",
    title: "All-India JEE Precision Contest",
    tagline: "Precision Arena",
    level: 3,
    exam: "JEE Main & Advanced",
    category: "Engineering",
    entryFee: 79,
    prizePool: 553000,
    totalCollection: 790000,
    platformMargin: 237000,
    participants: 8450,
    maxParticipants: 10000,
    seatsAvailable: 1550,
    difficulty: "Apex",
    date: "July 18, 2026",
    time: "10:00 AM",
    duration: "3h 00m",
    status: "upcoming",
    bannerGradient: "from-violet-500/20 via-purple-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 17, 2026 11:59 PM",
    overview: "All-India JEE Precision Contest replicates official NTA/IIT JEE exam conditions under proctored lockdown for verified national standing percentiles.",
    eligibility: "JEE Main & Advanced aspirants across India.",
    structure: [
      "90 NTA & IIT Pattern Questions across PCM",
      "Full camera & proctored proctoring feed",
      "Audited Row-Level Security percentile evaluation"
    ],
    syllabus: [],
    rewards: [
      { rank: "Rank 1", prize: "₹1,25,000 Cash + Precision Supreme Trophy", recognition: "All-India Topper" }
    ],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 2. CIVIL SERVICES STREAM (UPSC CSE & STATE PCS) - LEVELS 1 TO 5
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "upsc-foundation-sprint",
    slug: "upsc-foundation-sprint",
    title: "UPSC CSE Prelims Foundation Speed Sprint",
    tagline: "Foundation Sprint",
    level: 1,
    exam: "UPSC CSE Prelims",
    category: "Civil Services",
    entryFee: 99,
    prizePool: 103950,
    totalCollection: 148500,
    platformMargin: 44550,
    participants: 1100,
    maxParticipants: 1500,
    seatsAvailable: 400,
    difficulty: "Prime",
    date: "July 12, 2026",
    time: "09:30 AM",
    duration: "1h 30m",
    status: "upcoming",
    bannerGradient: "from-amber-500/20 via-yellow-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 11, 2026 11:59 PM",
    overview: "UPSC CSE Prelims Foundation Speed Sprint tests General Studies GS Paper 1 fundamentals, polity, history, and current affairs recall speed.",
    eligibility: "Open to UPSC CSE & State PCS candidates.",
    structure: [
      "50 General Studies GS-1 Calibrated Questions",
      "Instant Accuracy & Score Analytics",
      "Proctored sandbox environment"
    ],
    syllabus: syllabusByContest["upsc-elite"] || [],
    rewards: rewardsByContest["upsc-elite"] || [],
    rules: generalContestRules[1].points,
    timeline: scheduleByContest["upsc-elite"] || [],
    faq: globalFAQContent
  },
  {
    id: "upsc-analytical-cup",
    slug: "upsc-analytical-cup",
    title: "UPSC Civil Services Analytical Reasoning Cup",
    tagline: "Analytical Cup",
    level: 2,
    exam: "UPSC CSE Prelims",
    category: "Civil Services",
    entryFee: 89,
    prizePool: 311500,
    totalCollection: 445000,
    platformMargin: 133500,
    participants: 3950,
    maxParticipants: 5000,
    seatsAvailable: 1050,
    difficulty: "Elite",
    date: "July 15, 2026",
    time: "02:00 PM",
    duration: "2h 00m",
    status: "upcoming",
    bannerGradient: "from-blue-500/20 via-sky-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 14, 2026 11:59 PM",
    overview: "UPSC Civil Services Analytical Reasoning Cup focuses on statement-based questions, elimination techniques, and economics/environment analytical depth.",
    eligibility: "UPSC Prelims aspirants.",
    structure: [
      "60 Statement-Based GS Questions",
      "Standard UPSC 1/3 Negative Marking"
    ],
    syllabus: [],
    rewards: [],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },
  {
    id: "upsc-precision-contest",
    slug: "upsc-precision-contest",
    title: "All-India UPSC Prelims Precision Contest",
    tagline: "Precision Arena",
    level: 3,
    exam: "UPSC CSE Prelims",
    category: "Civil Services",
    entryFee: 79,
    prizePool: 553000,
    totalCollection: 790000,
    platformMargin: 237000,
    participants: 8100,
    maxParticipants: 10000,
    seatsAvailable: 1900,
    difficulty: "Apex",
    date: "July 18, 2026",
    time: "10:00 AM",
    duration: "2h 00m",
    status: "upcoming",
    bannerGradient: "from-violet-500/20 via-purple-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 17, 2026 11:59 PM",
    overview: "All-India UPSC Prelims Precision Contest features 100 questions modeled on exact UPSC difficulty to provide national merit percentiles.",
    eligibility: "UPSC Civil Services aspirants.",
    structure: [
      "100 GS-1 Questions",
      "Proctored lockdown proctoring"
    ],
    syllabus: [],
    rewards: [],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 3. MEDICAL STREAM (NEET UG & NEET PG) - LEVELS 1 TO 5
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "neet-foundation-sprint",
    slug: "neet-foundation-sprint",
    title: "NEET Medical Foundation Speed Sprint",
    tagline: "Foundation Sprint",
    level: 1,
    exam: "NEET UG",
    category: "Medical Sciences",
    entryFee: 99,
    prizePool: 103950,
    totalCollection: 148500,
    platformMargin: 44550,
    participants: 1300,
    maxParticipants: 1500,
    seatsAvailable: 200,
    difficulty: "Prime",
    date: "July 12, 2026",
    time: "09:30 AM",
    duration: "1h 30m",
    status: "upcoming",
    bannerGradient: "from-amber-500/20 via-yellow-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 11, 2026 11:59 PM",
    overview: "NEET Medical Foundation Speed Sprint tests NCERT Biology, Chemistry, and Physics fundamentals with high-speed recall questions.",
    eligibility: "NEET UG aspirants.",
    structure: [
      "50 NCERT High-Yield Biology, Physics & Chemistry Questions",
      "Instant Score Breakdown"
    ],
    syllabus: syllabusByContest["neet-prime"] || [],
    rewards: rewardsByContest["neet-prime"] || [],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },
  {
    id: "neet-analytical-cup",
    slug: "neet-analytical-cup",
    title: "NEET Medical Analytical Reasoning Cup",
    tagline: "Analytical Cup",
    level: 2,
    exam: "NEET UG",
    category: "Medical Sciences",
    entryFee: 89,
    prizePool: 311500,
    totalCollection: 445000,
    platformMargin: 133500,
    participants: 4200,
    maxParticipants: 5000,
    seatsAvailable: 800,
    difficulty: "Elite",
    date: "July 15, 2026",
    time: "02:00 PM",
    duration: "2h 00m",
    status: "upcoming",
    bannerGradient: "from-blue-500/20 via-sky-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 14, 2026 11:59 PM",
    overview: "NEET Medical Analytical Reasoning Cup evaluates multi-concept Physics numericals and Assertion-Reasoning Biology questions.",
    eligibility: "NEET UG candidates.",
    structure: [
      "60 Assertion-Reasoning & Multi-Step Questions"
    ],
    syllabus: [],
    rewards: [],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },
  {
    id: "neet-precision-contest",
    slug: "neet-precision-contest",
    title: "All-India NEET Precision Contest",
    tagline: "Precision Arena",
    level: 3,
    exam: "NEET UG",
    category: "Medical Sciences",
    entryFee: 79,
    prizePool: 553000,
    totalCollection: 790000,
    platformMargin: 237000,
    participants: 8600,
    maxParticipants: 10000,
    seatsAvailable: 1400,
    difficulty: "Apex",
    date: "July 18, 2026",
    time: "10:00 AM",
    duration: "3h 20m",
    status: "upcoming",
    bannerGradient: "from-rose-500/20 via-pink-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 17, 2026 11:59 PM",
    overview: "All-India NEET Precision Contest simulates official 200-question NTA paper format under strict proctored timer.",
    eligibility: "NEET UG candidates across India.",
    structure: [
      "180 Attemptable Questions across PCB",
      "Full camera proctoring"
    ],
    syllabus: [],
    rewards: [],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 4. MANAGEMENT & LAW STREAMS (CAT / CLAT / GATE)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "cat-analytical-cup",
    slug: "cat-analytical-cup",
    title: "CAT Quantitative & Logic Analytics Cup",
    tagline: "Analytical Cup",
    level: 2,
    exam: "CAT",
    category: "Finance & Management",
    entryFee: 89,
    prizePool: 311500,
    totalCollection: 445000,
    platformMargin: 133500,
    participants: 3400,
    maxParticipants: 5000,
    seatsAvailable: 1600,
    difficulty: "Elite",
    date: "July 20, 2026",
    time: "04:00 PM",
    duration: "2h 00m",
    status: "upcoming",
    bannerGradient: "from-emerald-500/20 via-teal-500/10 to-transparent",
    language: "English",
    country: "International",
    isFeatured: false,
    isTrending: true,
    registrationDeadline: "July 19, 2026 11:59 PM",
    overview: "CAT Quantitative & Logic Analytics Cup evaluates Quantitative Aptitude, Data Interpretation, and Logical Reasoning speed under high time pressure.",
    eligibility: "MBA graduates, CAT & XAT candidates.",
    structure: [
      "66 IIM-Pattern QA & DILR Questions",
      "Sectional Timers"
    ],
    syllabus: [],
    rewards: [],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },
  {
    id: "clat-precision-contest",
    slug: "clat-precision-contest",
    title: "All-India Legal Reasoning & CLAT Contest",
    tagline: "Precision Arena",
    level: 3,
    exam: "CLAT",
    category: "Law",
    entryFee: 79,
    prizePool: 553000,
    totalCollection: 790000,
    platformMargin: 237000,
    participants: 4100,
    maxParticipants: 10000,
    seatsAvailable: 5900,
    difficulty: "Prime",
    date: "July 22, 2026",
    time: "11:00 AM",
    duration: "2h 00m",
    status: "upcoming",
    bannerGradient: "from-sky-500/20 via-blue-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: false,
    isTrending: false,
    registrationDeadline: "July 21, 2026 11:59 PM",
    overview: "All-India Legal Reasoning & CLAT Contest evaluates passage-based legal reasoning, constitutional law, and comprehension.",
    eligibility: "CLAT UG / PG candidates.",
    structure: [
      "120 Passage-Based Legal & Critical Reasoning Questions"
    ],
    syllabus: [],
    rewards: [],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },

  // ───────────────────────────────────────────────────────────────────────────
  // 5. APEX & GRAND NATIONAL CONTESTS - LEVELS 4 & 5
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "national-grandmaster-cup",
    slug: "national-grandmaster-cup",
    title: "National Grandmaster Academic Cup",
    tagline: "Grandmaster Cup",
    level: 4,
    exam: "JEE / NEET / UPSC All-India",
    category: "Engineering & Medical",
    entryFee: 59,
    prizePool: 1032500,
    totalCollection: 1475000,
    platformMargin: 442500,
    participants: 19850,
    maxParticipants: 25000,
    seatsAvailable: 5150,
    difficulty: "Apex",
    date: "July 22, 2026",
    time: "10:00 AM",
    duration: "3h 20m",
    status: "upcoming",
    bannerGradient: "from-emerald-500/20 via-teal-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 21, 2026 11:59 PM",
    overview: "National Grandmaster Academic Cup is the premier national exam cup bringing together 25,000 serious contenders across India for ₹10.32 Lakhs cash pool.",
    eligibility: "Open to all JEE, NEET & UPSC aspirants across India.",
    structure: [
      "100 Grandmaster Level Exam Questions",
      "AI-audited proctoring & fraud protection system",
      "Official Merit Certificates & cash reward payouts for top rankers"
    ],
    syllabus: [],
    rewards: [
      { rank: "Rank 1", prize: "₹2,50,000 Cash + Grandmaster Apex Trophy", recognition: "All-India Champion" },
      { rank: "Rank 2 - 25", prize: "₹25,000 Cash Package", recognition: "Top 25 National Ranks" },
      { rank: "Rank 26 - 250", prize: "₹2,000 Credits", recognition: "Percentile Honor Badge" }
    ],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  },
  {
    id: "grand-national-apex-league",
    slug: "grand-national-apex-league",
    title: "Grand National Apex Contest",
    tagline: "Grand National Apex",
    level: 5,
    exam: "Grand National Competition",
    category: "Grand National Tier 5",
    entryFee: 49,
    prizePool: 1715000,
    totalCollection: 2450000,
    platformMargin: 735000,
    participants: 39120,
    maxParticipants: 50000,
    seatsAvailable: 10880,
    difficulty: "Apex",
    date: "July 25, 2026",
    time: "02:00 PM",
    duration: "4h 00m",
    status: "upcoming",
    bannerGradient: "from-rose-500/20 via-pink-500/10 to-transparent",
    language: "English",
    country: "India",
    isFeatured: true,
    isTrending: true,
    registrationDeadline: "July 24, 2026 11:59 PM",
    overview: "Grand National Apex Contest is India's largest national academic contest with 50,000 seat capacity, ₹17.15 Lakhs prize pool, and official Ranker's League Academic Medals.",
    eligibility: "Open to all student contenders across India.",
    structure: [
      "120 Exam Questions across Physics, Chemistry, Math & GK",
      "Full proctored proctoring feed & proctor log",
      "Official Grand National Merit Certificates & Cash Rewards"
    ],
    syllabus: [],
    rewards: [
      { rank: "Rank 1", prize: "₹5,00,000 Cash + National Crown Trophy", recognition: "Grand National Apex Topper" },
      { rank: "Rank 2 - 50", prize: "₹15,000 Cash Package", recognition: "National Merit Laureate" }
    ],
    rules: generalContestRules[1].points,
    timeline: [],
    faq: globalFAQContent
  }
];
