// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/admin/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/agents">> = Specific
  const handler = {} as typeof import("../../app/admin/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/analytics/contests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics/contests">> = Specific
  const handler = {} as typeof import("../../app/admin/analytics/contests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/analytics/executive/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics/executive">> = Specific
  const handler = {} as typeof import("../../app/admin/analytics/executive/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/analytics/exports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics/exports">> = Specific
  const handler = {} as typeof import("../../app/admin/analytics/exports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/analytics/forecasting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics/forecasting">> = Specific
  const handler = {} as typeof import("../../app/admin/analytics/forecasting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../app/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/analytics/participants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics/participants">> = Specific
  const handler = {} as typeof import("../../app/admin/analytics/participants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/analytics/performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics/performance">> = Specific
  const handler = {} as typeof import("../../app/admin/analytics/performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/analytics/questions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics/questions">> = Specific
  const handler = {} as typeof import("../../app/admin/analytics/questions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/analytics/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics/reports">> = Specific
  const handler = {} as typeof import("../../app/admin/analytics/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/analytics/revenue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics/revenue">> = Specific
  const handler = {} as typeof import("../../app/admin/analytics/revenue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/communication/automation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/communication/automation">> = Specific
  const handler = {} as typeof import("../../app/admin/communication/automation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/communication/campaigns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/communication/campaigns">> = Specific
  const handler = {} as typeof import("../../app/admin/communication/campaigns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/communication/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/communication/events">> = Specific
  const handler = {} as typeof import("../../app/admin/communication/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/communication/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/communication/history">> = Specific
  const handler = {} as typeof import("../../app/admin/communication/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/communication/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/communication">> = Specific
  const handler = {} as typeof import("../../app/admin/communication/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/communication/queue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/communication/queue">> = Specific
  const handler = {} as typeof import("../../app/admin/communication/queue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/communication/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/communication/templates">> = Specific
  const handler = {} as typeof import("../../app/admin/communication/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/communication/workflows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/communication/workflows">> = Specific
  const handler = {} as typeof import("../../app/admin/communication/workflows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/contests/[contestId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/contests/[contestId]">> = Specific
  const handler = {} as typeof import("../../app/admin/contests/[contestId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/contests/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/contests/calendar">> = Specific
  const handler = {} as typeof import("../../app/admin/contests/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/contests/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/contests/create">> = Specific
  const handler = {} as typeof import("../../app/admin/contests/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/contests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/contests">> = Specific
  const handler = {} as typeof import("../../app/admin/contests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/contests/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/contests/templates">> = Specific
  const handler = {} as typeof import("../../app/admin/contests/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/evaluation/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/evaluation/jobs">> = Specific
  const handler = {} as typeof import("../../app/admin/evaluation/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/evaluation/live/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/evaluation/live">> = Specific
  const handler = {} as typeof import("../../app/admin/evaluation/live/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/evaluation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/evaluation">> = Specific
  const handler = {} as typeof import("../../app/admin/evaluation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/finance/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance/overview">> = Specific
  const handler = {} as typeof import("../../app/admin/finance/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance">> = Specific
  const handler = {} as typeof import("../../app/admin/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/finance/platform-fees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance/platform-fees">> = Specific
  const handler = {} as typeof import("../../app/admin/finance/platform-fees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/finance/prize-distribution/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance/prize-distribution">> = Specific
  const handler = {} as typeof import("../../app/admin/finance/prize-distribution/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/finance/refunds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance/refunds">> = Specific
  const handler = {} as typeof import("../../app/admin/finance/refunds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/finance/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance/reports">> = Specific
  const handler = {} as typeof import("../../app/admin/finance/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/finance/subscriptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance/subscriptions">> = Specific
  const handler = {} as typeof import("../../app/admin/finance/subscriptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/finance/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance/transactions">> = Specific
  const handler = {} as typeof import("../../app/admin/finance/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/finance/wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance/wallet">> = Specific
  const handler = {} as typeof import("../../app/admin/finance/wallet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/finance/withdrawals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance/withdrawals">> = Specific
  const handler = {} as typeof import("../../app/admin/finance/withdrawals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/overview">> = Specific
  const handler = {} as typeof import("../../app/admin/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/papers/[paperId]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/papers/[paperId]/edit">> = Specific
  const handler = {} as typeof import("../../app/admin/papers/[paperId]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/papers/[paperId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/papers/[paperId]">> = Specific
  const handler = {} as typeof import("../../app/admin/papers/[paperId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/papers/blueprints/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/papers/blueprints">> = Specific
  const handler = {} as typeof import("../../app/admin/papers/blueprints/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/papers/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/papers/create">> = Specific
  const handler = {} as typeof import("../../app/admin/papers/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/papers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/papers">> = Specific
  const handler = {} as typeof import("../../app/admin/papers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/papers/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/papers/review">> = Specific
  const handler = {} as typeof import("../../app/admin/papers/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/papers/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/papers/templates">> = Specific
  const handler = {} as typeof import("../../app/admin/papers/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/papers/versions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/papers/versions">> = Specific
  const handler = {} as typeof import("../../app/admin/papers/versions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/participants/[participantId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/participants/[participantId]">> = Specific
  const handler = {} as typeof import("../../app/admin/participants/[participantId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/participants/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/participants/activity">> = Specific
  const handler = {} as typeof import("../../app/admin/participants/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/participants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/participants">> = Specific
  const handler = {} as typeof import("../../app/admin/participants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/participants/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/participants/search">> = Specific
  const handler = {} as typeof import("../../app/admin/participants/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/participants/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/participants/security">> = Specific
  const handler = {} as typeof import("../../app/admin/participants/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/participants/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/participants/support">> = Specific
  const handler = {} as typeof import("../../app/admin/participants/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/participants/verifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/participants/verifications">> = Specific
  const handler = {} as typeof import("../../app/admin/participants/verifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/prize-engine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/prize-engine">> = Specific
  const handler = {} as typeof import("../../app/admin/prize-engine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/question-bank/[questionId]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/question-bank/[questionId]/edit">> = Specific
  const handler = {} as typeof import("../../app/admin/question-bank/[questionId]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/question-bank/[questionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/question-bank/[questionId]">> = Specific
  const handler = {} as typeof import("../../app/admin/question-bank/[questionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/question-bank/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/question-bank/create">> = Specific
  const handler = {} as typeof import("../../app/admin/question-bank/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/question-bank/duplicates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/question-bank/duplicates">> = Specific
  const handler = {} as typeof import("../../app/admin/question-bank/duplicates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/question-bank/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/question-bank/import">> = Specific
  const handler = {} as typeof import("../../app/admin/question-bank/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/question-bank/media/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/question-bank/media">> = Specific
  const handler = {} as typeof import("../../app/admin/question-bank/media/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/question-bank/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/question-bank">> = Specific
  const handler = {} as typeof import("../../app/admin/question-bank/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/question-bank/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/question-bank/review">> = Specific
  const handler = {} as typeof import("../../app/admin/question-bank/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/question-bank/trash/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/question-bank/trash">> = Specific
  const handler = {} as typeof import("../../app/admin/question-bank/trash/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/rankings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/rankings">> = Specific
  const handler = {} as typeof import("../../app/admin/rankings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/results">> = Specific
  const handler = {} as typeof import("../../app/admin/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/results/publish/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/results/publish">> = Specific
  const handler = {} as typeof import("../../app/admin/results/publish/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/results/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/results/review">> = Specific
  const handler = {} as typeof import("../../app/admin/results/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/system/backups/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/system/backups">> = Specific
  const handler = {} as typeof import("../../app/admin/system/backups/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/system/environment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/system/environment">> = Specific
  const handler = {} as typeof import("../../app/admin/system/environment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/system/general/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/system/general">> = Specific
  const handler = {} as typeof import("../../app/admin/system/general/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/system/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/system/integrations">> = Specific
  const handler = {} as typeof import("../../app/admin/system/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/system/jobs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/system/jobs">> = Specific
  const handler = {} as typeof import("../../app/admin/system/jobs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/system/localization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/system/localization">> = Specific
  const handler = {} as typeof import("../../app/admin/system/localization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/system/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/system/logs">> = Specific
  const handler = {} as typeof import("../../app/admin/system/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/system/maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/system/maintenance">> = Specific
  const handler = {} as typeof import("../../app/admin/system/maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/system/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/system">> = Specific
  const handler = {} as typeof import("../../app/admin/system/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/system/permissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/system/permissions">> = Specific
  const handler = {} as typeof import("../../app/admin/system/permissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/system/platform/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/system/platform">> = Specific
  const handler = {} as typeof import("../../app/admin/system/platform/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/system/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/system/roles">> = Specific
  const handler = {} as typeof import("../../app/admin/system/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/system/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/system/security">> = Specific
  const handler = {} as typeof import("../../app/admin/system/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/system/storage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/system/storage">> = Specific
  const handler = {} as typeof import("../../app/admin/system/storage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/design-system/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design-system">> = Specific
  const handler = {} as typeof import("../../app/design-system/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
