// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/auth/complete-profile" | "/auth/forgot-access" | "/auth/login" | "/auth/register" | "/auth/reset-password" | "/auth/session-expired" | "/auth/verify-otp" | "/blog" | "/blog/[slug]" | "/careers" | "/championships" | "/championships/[category]" | "/community-guidelines" | "/contact" | "/contests" | "/contests/[slug]" | "/contests/[slug]/admit-card" | "/contests/[slug]/checkout" | "/contests/[slug]/confirmation" | "/contests/[slug]/register" | "/cookie-policy" | "/cookies" | "/dashboard" | "/dashboard/achievements" | "/dashboard/announcements" | "/dashboard/my-contests" | "/dashboard/notifications" | "/dashboard/performance" | "/dashboard/prize-matrix-architect" | "/dashboard/profile" | "/dashboard/results" | "/dashboard/settings" | "/dashboard/wallet" | "/dashboard/wallet/payment-methods" | "/dashboard/wallet/payout-history" | "/dashboard/wallet/transactions" | "/dashboard/wallet/withdraw" | "/fair-competition-policy" | "/help" | "/honor-code" | "/leaderboard" | "/live" | "/live/[contestSlug]" | "/live/[contestSlug]/access" | "/live/[contestSlug]/exam" | "/live/[contestSlug]/lobby" | "/live/[contestSlug]/summary" | "/live/[contestSlug]/workspace" | "/press" | "/pricing" | "/privacy-policy" | "/profile/[username]" | "/profile/settings" | "/refund-policy" | "/results" | "/results/[contestId]" | "/rewards" | "/terms" | "/terms-of-service" | "/verification" | "/verification-terms"
type AppRouteHandlerRoutes = "/api/auth/avatar" | "/api/auth/check-username" | "/api/auth/contests/register" | "/api/auth/contests/verify-device" | "/api/auth/notifications/actions" | "/api/auth/notifications/preferences" | "/api/auth/notifications/read-all" | "/api/auth/profile" | "/api/auth/sessions" | "/api/auth/wallet/bank-accounts" | "/api/auth/wallet/deposit" | "/api/auth/wallet/upi-accounts" | "/api/auth/wallet/withdrawal" | "/api/supabase/health" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/auth" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/api/auth/avatar": {}
  "/api/auth/check-username": {}
  "/api/auth/contests/register": {}
  "/api/auth/contests/verify-device": {}
  "/api/auth/notifications/actions": {}
  "/api/auth/notifications/preferences": {}
  "/api/auth/notifications/read-all": {}
  "/api/auth/profile": {}
  "/api/auth/sessions": {}
  "/api/auth/wallet/bank-accounts": {}
  "/api/auth/wallet/deposit": {}
  "/api/auth/wallet/upi-accounts": {}
  "/api/auth/wallet/withdrawal": {}
  "/api/supabase/health": {}
  "/auth": {}
  "/auth/callback": {}
  "/auth/complete-profile": {}
  "/auth/forgot-access": {}
  "/auth/login": {}
  "/auth/register": {}
  "/auth/reset-password": {}
  "/auth/session-expired": {}
  "/auth/verify-otp": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/careers": {}
  "/championships": {}
  "/championships/[category]": { "category": string; }
  "/community-guidelines": {}
  "/contact": {}
  "/contests": {}
  "/contests/[slug]": { "slug": string; }
  "/contests/[slug]/admit-card": { "slug": string; }
  "/contests/[slug]/checkout": { "slug": string; }
  "/contests/[slug]/confirmation": { "slug": string; }
  "/contests/[slug]/register": { "slug": string; }
  "/cookie-policy": {}
  "/cookies": {}
  "/dashboard": {}
  "/dashboard/achievements": {}
  "/dashboard/announcements": {}
  "/dashboard/my-contests": {}
  "/dashboard/notifications": {}
  "/dashboard/performance": {}
  "/dashboard/prize-matrix-architect": {}
  "/dashboard/profile": {}
  "/dashboard/results": {}
  "/dashboard/settings": {}
  "/dashboard/wallet": {}
  "/dashboard/wallet/payment-methods": {}
  "/dashboard/wallet/payout-history": {}
  "/dashboard/wallet/transactions": {}
  "/dashboard/wallet/withdraw": {}
  "/fair-competition-policy": {}
  "/help": {}
  "/honor-code": {}
  "/leaderboard": {}
  "/live": {}
  "/live/[contestSlug]": { "contestSlug": string; }
  "/live/[contestSlug]/access": { "contestSlug": string; }
  "/live/[contestSlug]/exam": { "contestSlug": string; }
  "/live/[contestSlug]/lobby": { "contestSlug": string; }
  "/live/[contestSlug]/summary": { "contestSlug": string; }
  "/live/[contestSlug]/workspace": { "contestSlug": string; }
  "/press": {}
  "/pricing": {}
  "/privacy-policy": {}
  "/profile/[username]": { "username": string; }
  "/profile/settings": {}
  "/refund-policy": {}
  "/results": {}
  "/results/[contestId]": { "contestId": string; }
  "/rewards": {}
  "/terms": {}
  "/terms-of-service": {}
  "/verification": {}
  "/verification-terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/auth": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
