// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/complete-profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/complete-profile">> = Specific
  const handler = {} as typeof import("../../app/auth/complete-profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/forgot-access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/forgot-access">> = Specific
  const handler = {} as typeof import("../../app/auth/forgot-access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/register">> = Specific
  const handler = {} as typeof import("../../app/auth/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../app/auth/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/session-expired/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/session-expired">> = Specific
  const handler = {} as typeof import("../../app/auth/session-expired/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/verify-otp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/verify-otp">> = Specific
  const handler = {} as typeof import("../../app/auth/verify-otp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/careers">> = Specific
  const handler = {} as typeof import("../../app/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/championships/[category]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/championships/[category]">> = Specific
  const handler = {} as typeof import("../../app/championships/[category]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/championships/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/championships">> = Specific
  const handler = {} as typeof import("../../app/championships/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/community-guidelines/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community-guidelines">> = Specific
  const handler = {} as typeof import("../../app/community-guidelines/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contests/[slug]/admit-card/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contests/[slug]/admit-card">> = Specific
  const handler = {} as typeof import("../../app/contests/[slug]/admit-card/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contests/[slug]/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contests/[slug]/checkout">> = Specific
  const handler = {} as typeof import("../../app/contests/[slug]/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contests/[slug]/confirmation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contests/[slug]/confirmation">> = Specific
  const handler = {} as typeof import("../../app/contests/[slug]/confirmation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contests/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contests/[slug]">> = Specific
  const handler = {} as typeof import("../../app/contests/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contests/[slug]/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contests/[slug]/register">> = Specific
  const handler = {} as typeof import("../../app/contests/[slug]/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contests">> = Specific
  const handler = {} as typeof import("../../app/contests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cookie-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cookie-policy">> = Specific
  const handler = {} as typeof import("../../app/cookie-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cookies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cookies">> = Specific
  const handler = {} as typeof import("../../app/cookies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/achievements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/achievements">> = Specific
  const handler = {} as typeof import("../../app/dashboard/achievements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/announcements">> = Specific
  const handler = {} as typeof import("../../app/dashboard/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/my-contests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/my-contests">> = Specific
  const handler = {} as typeof import("../../app/dashboard/my-contests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/notifications">> = Specific
  const handler = {} as typeof import("../../app/dashboard/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/performance">> = Specific
  const handler = {} as typeof import("../../app/dashboard/performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/prize-matrix-architect/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/prize-matrix-architect">> = Specific
  const handler = {} as typeof import("../../app/dashboard/prize-matrix-architect/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/profile">> = Specific
  const handler = {} as typeof import("../../app/dashboard/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/results">> = Specific
  const handler = {} as typeof import("../../app/dashboard/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/wallet">> = Specific
  const handler = {} as typeof import("../../app/dashboard/wallet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/wallet/payment-methods/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/wallet/payment-methods">> = Specific
  const handler = {} as typeof import("../../app/dashboard/wallet/payment-methods/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/wallet/payout-history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/wallet/payout-history">> = Specific
  const handler = {} as typeof import("../../app/dashboard/wallet/payout-history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/wallet/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/wallet/transactions">> = Specific
  const handler = {} as typeof import("../../app/dashboard/wallet/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/wallet/withdraw/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/wallet/withdraw">> = Specific
  const handler = {} as typeof import("../../app/dashboard/wallet/withdraw/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/fair-competition-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fair-competition-policy">> = Specific
  const handler = {} as typeof import("../../app/fair-competition-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/help">> = Specific
  const handler = {} as typeof import("../../app/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/honor-code/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/honor-code">> = Specific
  const handler = {} as typeof import("../../app/honor-code/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leaderboard">> = Specific
  const handler = {} as typeof import("../../app/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/live/[contestSlug]/access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/live/[contestSlug]/access">> = Specific
  const handler = {} as typeof import("../../app/live/[contestSlug]/access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/live/[contestSlug]/exam/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/live/[contestSlug]/exam">> = Specific
  const handler = {} as typeof import("../../app/live/[contestSlug]/exam/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/live/[contestSlug]/lobby/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/live/[contestSlug]/lobby">> = Specific
  const handler = {} as typeof import("../../app/live/[contestSlug]/lobby/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/live/[contestSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/live/[contestSlug]">> = Specific
  const handler = {} as typeof import("../../app/live/[contestSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/live/[contestSlug]/summary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/live/[contestSlug]/summary">> = Specific
  const handler = {} as typeof import("../../app/live/[contestSlug]/summary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/live/[contestSlug]/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/live/[contestSlug]/workspace">> = Specific
  const handler = {} as typeof import("../../app/live/[contestSlug]/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/live/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/live">> = Specific
  const handler = {} as typeof import("../../app/live/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/press/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/press">> = Specific
  const handler = {} as typeof import("../../app/press/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../app/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/[username]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/[username]">> = Specific
  const handler = {} as typeof import("../../app/profile/[username]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/settings">> = Specific
  const handler = {} as typeof import("../../app/profile/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/refund-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/refund-policy">> = Specific
  const handler = {} as typeof import("../../app/refund-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/results/[contestId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/results/[contestId]">> = Specific
  const handler = {} as typeof import("../../app/results/[contestId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/results">> = Specific
  const handler = {} as typeof import("../../app/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/rewards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rewards">> = Specific
  const handler = {} as typeof import("../../app/rewards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms-of-service/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms-of-service">> = Specific
  const handler = {} as typeof import("../../app/terms-of-service/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/verification-terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verification-terms">> = Specific
  const handler = {} as typeof import("../../app/verification-terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/verification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verification">> = Specific
  const handler = {} as typeof import("../../app/verification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/avatar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/avatar">> = Specific
  const handler = {} as typeof import("../../app/api/auth/avatar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/check-username/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/check-username">> = Specific
  const handler = {} as typeof import("../../app/api/auth/check-username/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/contests/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/contests/register">> = Specific
  const handler = {} as typeof import("../../app/api/auth/contests/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/contests/verify-device/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/contests/verify-device">> = Specific
  const handler = {} as typeof import("../../app/api/auth/contests/verify-device/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/notifications/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/notifications/actions">> = Specific
  const handler = {} as typeof import("../../app/api/auth/notifications/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/notifications/preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/notifications/preferences">> = Specific
  const handler = {} as typeof import("../../app/api/auth/notifications/preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/notifications/read-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/notifications/read-all">> = Specific
  const handler = {} as typeof import("../../app/api/auth/notifications/read-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/profile">> = Specific
  const handler = {} as typeof import("../../app/api/auth/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/sessions">> = Specific
  const handler = {} as typeof import("../../app/api/auth/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/wallet/bank-accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/wallet/bank-accounts">> = Specific
  const handler = {} as typeof import("../../app/api/auth/wallet/bank-accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/wallet/deposit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/wallet/deposit">> = Specific
  const handler = {} as typeof import("../../app/api/auth/wallet/deposit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/wallet/upi-accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/wallet/upi-accounts">> = Specific
  const handler = {} as typeof import("../../app/api/auth/wallet/upi-accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/wallet/withdrawal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/wallet/withdrawal">> = Specific
  const handler = {} as typeof import("../../app/api/auth/wallet/withdrawal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/concept-bank/coverage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concept-bank/coverage">> = Specific
  const handler = {} as typeof import("../../app/api/concept-bank/coverage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/concept-bank/exams/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concept-bank/exams">> = Specific
  const handler = {} as typeof import("../../app/api/concept-bank/exams/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/concept-bank/templates/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concept-bank/templates/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/concept-bank/templates/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/concept-bank/templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concept-bank/templates">> = Specific
  const handler = {} as typeof import("../../app/api/concept-bank/templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/concept-bank/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concept-bank/validate">> = Specific
  const handler = {} as typeof import("../../app/api/concept-bank/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/supabase/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/supabase/health">> = Specific
  const handler = {} as typeof import("../../app/api/supabase/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/auth/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../app/auth/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
